### ISSUE TITLE
Unable to checkout 'chatsecure-push' submodule commit 'fdd6a68ccd766335143a2675fa5bb6df79cb0976'

### ISSUE THREAD

**Issue by jasonwcfan** [zom/Zom-Android-XMPP#101]
I'm getting the 
`fatal: reference is not a tree: fdd6a68ccd766335143a2675fa5bb6df79cb0976` 
`Unable to checkout 'fdd6a68ccd766335143a2675fa5bb6df79cb0976' in submodule path 'chatsecure-push'`

error when I try to update the submodule.

**Comment by n8fr8** [comment]
It should be tied to here:
https://github.com/guardianproject/ChatSecure-Push-Android/tree/fdd6a68ccd766335143a2675fa5bb6df79cb0976

**Comment by n8fr8** [comment]
Try again with the latest push. Just updated.
