### ISSUE TITLE
Zom Crashes when opening chat with contact with Username in Tibetan

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-Android-XMPP#110]
Where I am now, I invited someone using LG G Pad 7.0 LTE OS 5.0.2 to Zom. He downloaded from Playstore and created user name in Tibetan.

In the contact, his initial appears as question mark.

Each time we (myself and another person who added him) clicked on the message he sent, Zom crashes.

**Comment by n8fr8** [comment]
Eek! Will look into this right away.

**Comment by n8fr8** [comment]
should be fixed now
