### ISSUE TITLE
Implement Omemo / Axolotl

### ISSUE THREAD

**Issue by dreamflasher** [zom/Zom-Android-XMPP#119]
It would be great if ZOM supported [Omemo](http://conversations.im/omemo/) or [Signal](https://github.com/WhisperSystems/libsignal-protocol-c/) or [Olm](https://github.com/matrix-org/olm) protocol for multi-party, multi-device e2e. Ideally interop with [ChatSecure/Signal](https://github.com/ChatSecure/ChatSecure-iOS/issues/376) and Conversations.

**Comment by n8fr8** [comment]
It is coming, and we plan for full interop with Conversations and ChatSecure for sure.

**Comment by rabbit111** [comment]
Will Zom interop with pidgin+otr like chatsecure does?

**Comment by n8fr8** [comment]
It already does today. Zom is standard XMPP + OTR and works great with Pidgin.

**Comment by rabbit111** [comment]
In my opinion chatsecure (guardian repo via f-droid, 14.2.3) works great. Unfortunately ZOM (15.0.1.925)  not yet.  
Attempt to start encryption takes too long, often with no success (in two directions).
The same problem is with verification by question.

**Comment by n8fr8** [comment]
That is really strange. Most people have seen the opposite - Zom encryption is much more automatic and seamless.

Are you using Zom to Zom, or with another app?

**Comment by dreamflasher** [comment]
I'm sorry to say, but isn't this a bit off-topic?

**Comment by n8fr8** [comment]
Sure, @rabbit111 maybe you can create a new ticket for us to debug your OTR issues? https://github.com/zom/Zom-Android/issues

**Comment by rabbit111** [comment]
@n8fr8 ok

**Comment by dreamflasher** [comment]
With the latest updates here https://github.com/ChatSecure/ChatSecure-iOS/issues/376#issuecomment-257625846 when do you plan to work on the Zom integration?

**Comment by h-2** [comment]
Would be nice to have a mobile client for android that supports omemo and activates it by default so I can recommend it to non-nerds. Unfortunately Conversations is not an option (try telling people to choose between different cyphers for every user :disappointed:  ).

**Comment by vanitasvitae** [comment]
I'm working on an OMEMO module for Smack (which Zom is based on) as part of my bachelors thesis, so Zom might use this in the future.

**Comment by n8fr8** [comment]
Plans are underway.... the Zom iOS app wil get ChatSecure iOS OMEMO capability in the next few weeks.

**Comment by 2Belette** [comment]
that's a good news!
any idea when we can expect it available on the applestore? (and which version will support it?)

**Comment by vanitasvitae** [comment]
> applestore

This is the Android Project tracker
Eidt: Whoopsy, context matters :D

**Comment by 2Belette** [comment]
yep I was too quick ! I meant on android

**Comment by mimi89999** [comment]
Any plans on when it will be implemented in Zom Android?

Is it implemented in the iOS version already?

**Comment by n8fr8** [comment]
Zom iOS now has the OMEMO code integrated. We plan to release it by early April with OMEMO enabled. We are simultaneously working on integrated Smack-OMEMO project in Zom Android, as well, with at least a public beta in April.

**Comment by vanitasvitae** [comment]
> We are simultaneously working on integrated Smack-OMEMO project in Zom Android

Are you talking about [this](https://github.com/vanitasvitae/smack-omemo)?

**Comment by n8fr8** [comment]
Yes, though we fully understand it is a work in progress. We hope to help move it along to production ready as you are ready for it to be.

**Comment by vanitasvitae** [comment]
I'd love to get the client developers perspective on the module :)

**Comment by n8fr8** [comment]
Progress! https://github.com/n8fr8/Zom-Android/tree/dev_omemo

**Comment by n8fr8** [comment]
(working but not pretty!)

**Comment by Simon0Harms** [comment]
Will you post in this Thread if OMEMO is gone life for Android?
I am Waiting for this feature. I want to start using Zom.

**Comment by mimi89999** [comment]
@JokerGermany Yes. It is in the alphas, but it is **very** buggy.

**Comment by n8fr8** [comment]
Omemo is shipped and done! We will continue to improve as needed, but it works well now, fully interoperable with other Omemo apps.

**Comment by vanitasvitae** [comment]
@n8fr8 Do you still need help with OMEMO encrypted MUC?

**Comment by n8fr8** [comment]
Yes, absolutely. We are just finishing up a major update of our groupchat user interface and reliability now (15.3 now in beta!). Our next sprint in early October is OMEMO MUC. Got some cycles to contribute?

**Comment by vanitasvitae** [comment]
I'll see if I can help you :)
