### ISSUE TITLE
zom encryption

### ISSUE THREAD

**Issue by rabbit111** [zom/Zom-Android-XMPP#120]
In my opinion chatsecure (guardian repo via f-droid, 14.2.3) works great. Unfortunately ZOM (15.0.1.925) not yet.
Attempt to start encryption takes too long, often with no success (in two directions).
The same problem is with verification by question.

ZOM-chatsecure;chatsecure-ZOM; pidgin+OTR (Pidgin 2.11.0 (libpurple 2.11.0))-ZOM; ZOM-pidgin+OTR
XMPP servers: riseup, autistici, dukgo

**Comment by n8fr8** [comment]
We've made improvements to encryption startup and upgraded our dependent crypto libraries to spongycastle, etc. Please try our next public release to see if this has all improved for you.
