### ISSUE TITLE
ipad2 - conversation doesn't appear

### ISSUE THREAD

**Issue by rabbit111** [zom/Zom-Android-XMPP#121]
When I start conversation ZOM-pidgin, pidgin-ZOM text of conversation doesn't appear on ipad. All conversation appear on pidgin. When I click "send" on ZOM text appears on pidgin, but doesn't on Ipad. When I send text on pidgin to ZOM, it appears on pidgin as sent, but does not appear on ZOM. On chatsecure everything works.
Version - up to date via app-store.

**Comment by n8fr8** [comment]
This should be filed on the iOS bug tracker not Android. Can you reinput it there?
