### ISSUE TITLE
Translation glitch

### ISSUE THREAD

**Issue by ghost** [zom/Zom-Android-XMPP#130]
Settings -> Chat encryption. The dialog window says "Khansela" instead of OK. Version 15.0.1.925 on a Nexus 5 running latest Android 6.0.1, English US system locale or whatever it is called on Android.

**Comment by n8fr8** [comment]
Ah the old Khansela problem! Thanks for finding it. It is quite a silly bug.

**Comment by cstiens** [comment]
I believe this is the view we're referring to. Is that correct?

![screenshot_20170327-105301](https://cloud.githubusercontent.com/assets/1434597/24365503/c53ac46e-12db-11e7-83f2-68ad43e222d2.png)

**Comment by cstiens** [comment]
Closing this since we have updated translations.
