### ISSUE TITLE
Zom loses language setting frequently, reverting to English

### ISSUE THREAD

**Issue by mandree** [zom/Zom-Android-XMPP#146]
Depending on what I am doing, Zom (as ChatSecure before) loses the language setting and reverts to showing the UI mostly in English. Unfortunately I have never found a way to reproduce this setting.

**Comment by ejhuff** [comment]
I've seen zom (once) and chatsecure (many times) change language from English to something else.  I only notice when the copy paste etc. popup is active.  The word for copy is always the same and I'd recognize it but can't recall just now.

**Comment by n8fr8** [comment]
Dynamic language switching separate from the OS setting remains a dark art in Android. We'll review this and make sure we are using the latest, best methods.

**Comment by ejhuff** [comment]
I saw it again today in chatsecure, and ONLY the wording on the edit text context menu was in the wrong language.  I tried switching to Spanish and everything changed.  Good thing I knew where the language selection option is.  When the edit menu language is wrong, tapping English in settings fixes it.
