### ISSUE TITLE
Can't get beyond welcome bubble

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-Android-XMPP#148]
Hi Zom Support,

I installed Zom via Google Play, but can't get past the welcome bubble with the "Switch Language" and "Überspringen >>" texts. I tried tapping virtually everywhere and swiping in various directions: Nothing happens.
When I open the app via the info message (that says "Aktiviert und entsperrt") I get to the UI, but can't use it :-(

Any ideas how to solve this?
I tried it on a LG Nexus 5 and ASUS K015, but it behaves absolutely identical. I even tried the APK on the Nexus 5, but it is just the same - except for that it installes as ChatSecure...

**Comment by licaon-kter** [comment]
So this is fixed? i get this on 15.0.3-RC-3.
