### ISSUE TITLE
Key/fingerprint change of contact not detected

### ISSUE THREAD

**Issue by lluki** [zom/Zom-Android-XMPP#154]
I will have to try it again, but this looks like a very serious problem to me. When the key of contact changes, there is no visual feedback at all that this has happened. IMHO there should be a gigantic warning sign when one of the contacts changes his key.

Steps to reproduce:
- Set up ZOM account
- Connect to the account with Pidgin+OTR plugin
- Verify each others fingerprint, enjoy encryption, make sure with the "guard" icon that messages are encrypted.
- Shut down pidgin
- delete otr key, `rm .purple/otr.private_key`
- Start pidgin. go to plugin settings and generate a new key
- go back to the chat window with the client, click on start private chat,
- Enjoy encryption? No warning is printed in zom and the message gets the nice "guard" icon.

Expected behaviour:
- ZOM.im shows a warning that the fingerprint of a contact has changed.

I got the latest version from play store. I can't find any version or build id or so in the app.

**Comment by n8fr8** [comment]
Thank for the report. The logic and UI is there for the key state detection, but it must not be getting displayed when it should be. I will have someone look at it, and make sure this is fixed immediately.

**Comment by n8fr8** [comment]
We have worked to address this in our latest work on v15.2. The app will warn you if the remote contact is using an unverified key or "Secure Identity", and prompt you to verify it. We have some more ideas on how to handle these scenarios, but do want to find the right balance between confusing the user unnecessarily, and avoiding a man-in-the-middle attack.

https://github.com/zom/Zom-Android/releases/tag/15.0.1.933
