### ISSUE TITLE
OTR error: encryption error from a contact (between iOS & Android device)

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-Android-XMPP#156]
"I just installed Zom and pressed all my contacts to install it too, but I am getting a lot of error messages. I keep receiving the message OTR error: encryption error from a contact.

When i receive this message, do i need to ask the contact to send the message again, or will Zom automatically resend these messages?

Do you know why this error occurs? I am receiving messages, but one in six messages are an otr encryption error. We are both using zom, i am using android and the other person is using ios.

Is this error inherent to all apps which use otr encryption? Or will a different app work with less errors?"

**Comment by n8fr8** [comment]
Is this a support message from email?

**Comment by gekhung** [comment]
Yes

Tenchoe

**Comment by n8fr8** [comment]
This is now address and OTR sessions should only start once both sides are online and approved as friends.
