### ISSUE TITLE
Not be able to send an audio message in group?

### ISSUE THREAD

**Issue by Pezhin** [zom/Zom-Android-XMPP#159]
Hi, I want to send an audio message on my LG Nexus4 running Android 5.1.1. Photo below shows the state. When I click on the Microphone icon, nothing changes.

Do I miss anything?

![image](https://cloud.githubusercontent.com/assets/11862132/20195637/978cc9a6-a754-11e6-9dc4-540f6d06f5bf.png)

**Comment by n8fr8** [comment]
Group file sharing is coming in April/May. We need to support group encryption for this to work. We don't want to send unencrypted files.

**Comment by n8fr8** [comment]
This is now supported, for awhile now!
