### ISSUE TITLE
Can't add contact

### ISSUE THREAD

**Issue by lupa18** [zom/Zom-Android-XMPP#164]
We are using v 4.3 (google play) and we can't add new contact. We're using Oxygen and Cyanogenmod OS. 

We receive the contact address and click on it (or scan with QR) but can't pass "add friends" screen:

![photo_2016-11-17_16-46-52 rotado](https://cloud.githubusercontent.com/assets/463429/20404891/851937dc-ace5-11e6-852f-d539a84f3fd2.jpg)

We don't see the "Add button" or similar and finally contact is not added.

**Comment by n8fr8** [comment]
You press the arrow/enter button on the keyboard to submit the full XMPP/JabberID of the contact. 

That said, it is better to add contacts by exchanging invite links with them through email, sms, or by scanning QR codes. There is less room for mistakes, and you also receive their OTR fingerprint that way.
