### ISSUE TITLE
does suggest servers?

### ISSUE THREAD

**Issue by gwasher** [zom/Zom-Android-XMPP#165]
Does zom select  servers from the mostly- or all green column tested servers via

https://gultsch.de/compliance.html 

![server xep as tested](https://cloud.githubusercontent.com/assets/23587635/20459754/34cd9ffe-ae82-11e6-8c92-67219312735b.png)

**Comment by n8fr8** [comment]
We keep an eye on common sites, and generate our own list which is built into the app. In the future, we are planning to make this more dynamic, and have the ability to update the server list, in case it changes.

**Comment by n8fr8** [comment]
Our list is here: https://github.com/zom/xmpp-server-list/blob/master/servers.json
