### ISSUE TITLE
Zom verification prompt coming up even if QR scanned

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#167]
QR scanning or tapping link does not set fingerprint as trusted

**Comment by cstiens** [comment]
@n8fr8 is it true that as long as a link is opened or QR code is scanned by one party, neither person should get a prompt to verify the other person?

We tested the adding friends/verification flows last week, and users do not get prompted to verify a contact when adding them via a link or scanning their QR code. This is true for Android and iOS.

**Comment by n8fr8** [comment]
When you tap a link or scan a code, you are automatically adding that person in to your list. You should not need to approve anything more.

**Comment by n8fr8** [comment]
In addition, since the fingerprint is included in the link, it should be marked as trusted.

**Comment by cstiens** [comment]
So for the person that you add via their link, do they need to verify you?

**Comment by n8fr8** [comment]
Well, they shouldn't either, since we also support the "Trust on First Use" (TOFU) model. The idea is that we won't bug you to verify, unless a key changes, and then you should. We still want those who want to manually extra verify to be able to do so at any time.

**Comment by n8fr8** [comment]
This is fixed now. The first key is TOFU. The second key prompts for verification. The current unverified key is now displayed properly in the contact view.
