### ISSUE TITLE
Missing translations from transifex

### ISSUE THREAD

**Issue by ghost** [zom/Zom-Android-XMPP#172]
Like Korean.
Already fully done in transifex for few months but seems like not updated in app.
I hope it will be updated soon

**Comment by anthologist** [comment]
Same here, seems like they don't care too much about transifex. Sometimes developers don't realize that people will never use an app that they can't read (many people are bad in english).

**Comment by n8fr8** [comment]
We do care, and make sure the app is available in the languages for the regions we focus on. That said, we put our code on Transifex because clearly we are interested in supporting many languages.

A new release is coming with the latest pulls from Transifex. Thanks for the help and interest!

**Comment by ghost** [comment]
Related issue which can also be closed when the strings are updated: https://github.com/zom/Zom-iOS/issues/243

It's a good idea to push/pull strings on a regular basis.

**Comment by n8fr8** [comment]
We had some issues with our "tx" command script that wasn't updating newer strings. These are now integrated in the commits on this PR.

**Comment by ghost** [comment]
Good to know, thanks.
