### ISSUE TITLE
Check+X bug is still happening

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#176]
happens for Jodie, and related to network connectivity and errors

**Comment by cstiens** [comment]
![screenshot_20170130-092448 1](https://cloud.githubusercontent.com/assets/1434597/23518415/03a77636-ff39-11e6-919d-d67aaed61dbc.png)

**Comment by n8fr8** [comment]
Messages will now not send until there is an active OTR/encryption session

**Comment by n8fr8** [comment]
All messages will now queue until OTR encryption is activate.

**Comment by cstiens** [comment]
We've had 2 more occurrences in version 15.1.0-alpha-1.

1. Lala’s messages weren’t sending. App crashed. She re-opened. Then could send messages.
Some messages disappeared after re-opening. She got the x-check on the first message she tried to send. The second message she sent disappeared.

2. Jodie’s phone crashed when she tried to send voice message (vm). After crashing, once she restarted, a message she’d sent before the vm showed up under the vm in the chat flow with a xcheck.

**Comment by n8fr8** [comment]
I've resolved this through debugging on the horrifically slow networks in North India. Before we would default to "Check", but now we default to "clock" or queued state. So if anything fails, it will always be queued for retry.
