### ISSUE TITLE
Duplicate notifications confirming friendship

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#177]
Notifications were sent at the same time. One with a nickname; one with the friend's full ID.

![screenshot_20170303-112843](https://cloud.githubusercontent.com/assets/1434597/23574723/5be1c612-0047-11e7-8a97-1b854e1efa96.png)

**Comment by n8fr8** [comment]
should be fixed

**Comment by cstiens** [comment]
Did not see this happening today.
