### ISSUE TITLE
Notify user when there is no internet

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#180]
See design in iOS thread: https://github.com/zom/Zom-iOS/issues/262

**Comment by n8fr8** [comment]
Add "Connect" button instead of "Ok" and take users to the accounts screen to change the "sign in" option

**Comment by cstiens** [comment]
I re-opened this because we need to streamline the look and behavior between iOS and Android.

**Comment by cstiens** [comment]
Working. Not streamlined with iOS. iOS doesn't ask you if you want to connect. The snackbar on Android works well.
