### ISSUE TITLE
Display friend request in conversations view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#184]
Currently friend requests show up in the friends list. They should be displayed in the conversations view instead to align with iOS.

**Comment by cstiens** [comment]
New Friend request still showing up in friends' view only.

**Comment by n8fr8** [comment]
The reason I keep delaying work on this ticket, is that it really doesn't make sense to show inbound friend quests in the conversation list. It is mixing two types of data (chats and contacts) into a single view, which is super funky to do. It also seems invasive if you don't want to talk to someone, that they popup in your conversations list. It is like they can start talking with you, even though you don't want them to.

Still, I am considering how to do this. If we have them show up in the conversations tab, does that mean we don't have it show up in the contacts tab? Or do we show it on both?

**Comment by n8fr8** [comment]
I've gotten this mostly working, but have some questions on the UI front that we can talk about next week. I am moving this ticket to the next sprint for the remaining work.
