### ISSUE TITLE
List new friends (pending) at the top of the friends list

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#185]
After sending a friend request, the potential friend added should be listed at the top of the list of friends as 'pending' until added. Once added, they are listed in alphabetical order.

**Comment by n8fr8** [comment]
We do this now, but we show them in the contact list, and not the conversation list. Are you seeing some other behavior?

**Comment by cstiens** [comment]
I just tested this. Incoming friend requests show at the top of the friends list with the actions to approve or deny the request. 

This issue is related to outgoing friend requests. Currently, after you add someone, they are listed in the friends list in alphabetical order. Rather than that, the contact should be listed at the top of the list as "username - Pending Approval'. I can attach a screenshot of how this is shown on ios.

**Comment by n8fr8** [comment]
Thanks for the clarification!

**Comment by cstiens** [comment]
You're welcome! Here's the screenshot — ![img_0105](https://cloud.githubusercontent.com/assets/1434597/24629752/c4fe04b2-187f-11e7-9292-259092889856.PNG)

**Comment by cstiens** [comment]
This still isn't happening on the user who is sending the new request after migration.

**Comment by n8fr8** [comment]
I think this is now happening, but we don't show any "pending approval" label

**Comment by n8fr8** [comment]
This should show "pending approval" now

**Comment by n8fr8** [comment]
though we show the text as the second line, instead of the xmpp user id, since it can get cut off if you append it to the nickname.
