### ISSUE TITLE
Pending approval not showing before friend approves me

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#187]
I added an iOS friend via QR code. Before tapping accept on iOS, the contact didn't show that it was pending approval on Android.

![screenshot_20170315-214950](https://cloud.githubusercontent.com/assets/1434597/23980528/2d5e0a9a-09ce-11e7-8fd0-b7ae328ea2d3.png)

**Comment by n8fr8** [comment]
We don't show that currently on Android. This would be an enhancement for sprint 2 then?

**Comment by cstiens** [comment]
Yes. We have a separate ticket for this #185 so I'll close this one.
