### ISSUE TITLE
Issues with auto-logging back in after losing internet connection

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#188]
I'm logged into my Zom account. When I turn off my internet connection, then turn it back on, the app doesn't connect automatically to the server. I have to clear all data within the app, and log back in for it to work.

Also, in the 'My Accounts' view, the toggle is turned on even though it says my network is offline.
![screenshot_20170315-210525](https://cloud.githubusercontent.com/assets/1434597/23980805/271bc1d4-09d0-11e7-919f-b404aa10f165.png)

**Comment by n8fr8** [comment]
Thanks. I've been debugging this regression and I think I've found the issue. There is a strange mix of wifi, 4g and going on/offline that is causing it. Fixed today in the next release.

**Comment by cstiens** [comment]
I believe this is fixed now. I've tested on 2 different phones, and they are auto-logging back in as they should.
