### ISSUE TITLE
new user new jid, please something well xep featured

### ISSUE THREAD

**Issue by loveuvfreight** [zom/Zom-Android-XMPP#189]
When i steer people to zom oft i find myself attempting to communicate with a feature-impaired base server like dukgo.com not allowing for offline messages for example

please draw recommend xmpp servers from the top of conversations' dev tested- and ranked matrix

https://gultsch.de/compliance_ranked.html

jabber.fr																																		
jabjab.de			(ybGood.de, 		planetjabber.de)								
wiuwiu.de													
5222.de																							
trashserver.net													
draugr.de													
deshalbfrei.org													
pimux.de													
jabber.cat													
mailbox.org													
fusselkater.org													
talker.to													
elaon.de													
jabber.systemli.org													
dismail.de													
jabber-germany.de													
creep.im													
chatme.im													
jabberzac.org																																													
fysh.in

**Comment by n8fr8** [comment]
Thanks will do. We are also now offering home.zom.im as a well featured XMPP server, and deprecating dukgo.com.

**Comment by jccheesey-2017** [comment]
Will zom team be expanding server capabilities to score more-green on that compliance test?

**Comment by n8fr8** [comment]
Yes, not sure when that was last generated, but we fully support PEP/OMEMO now, and will be adding support for MAM, and other features shortly. We also support "Cloud Push" messaging.

**Comment by n8fr8** [comment]
You can see the server list we recommend and support currently here: https://github.com/zom/xmpp-server-list/blob/master/servers.json

We will continue to update these.
