### ISSUE TITLE
zom crash when conversation QA for otr fingerprint

### ISSUE THREAD

**Issue by loveuvfreight** [zom/Zom-Android-XMPP#190]
existing conversations
friend new zom install

friend gets @home.zom.im 

friend manually adds my chinwag jid

various notifications 

me tries messaging friend

zom server announces crypto required 

me clicks verify in conversations

me elects to use question
fills question
fills answer
send

immediately zom crashes

repeatable always

**Comment by loveuvfreight** [comment]
zom restarts

friend sends me insecure text

me receives them

me cannot reply

friend is puzzled  [vexed], contacts me oob 

friend calls on phone, insists me use "normal texting"

friend clicks the cicle-i in chat
friend clicks box icon next to me JID
friend initiates QA verify

conversation in line chat prompts SMP
me provides challenge answer
zom verification complete

conversations prompts to verify



me unable to verify other than manually

me directs friend to tab to get friend fingerprint oob

conversations completes manual verification

me swnds conversations text, audio, photo, file

friend receives nothing

conversations indicates transfer 100%

friend receives nothing on zom

conversations showing padlock open

me sets padlock to otr

resends audio and photo

fail

friend receives filetransfer string of text

friend tries to copy the text to share with me

long click text block in zom
.click send arrow
conversations receives nothing

long click..zom
.. click share icon, share to clipboard app, email text

?FILETRANSFERv1:a6400000c5720addddf26719aee15..longhash

friend is growing weary of seeming dysfunction

friend uses zom green icon to send photo

check mark and shield in zom message

conversations receives nothing

friend sends sticker

2 checkmark and shield in zom

conversations receives text label of sticker

friend takes photo with zom

single checkmark shield in zom

me recieves nothing in conversations 

friend long clicks photo thumbmail in zom, clicks arrow thinking it resends 

nothing but whitespace appears in zom

single checkmark shoeld in zom

conversations receives nothing

friend clicks mic in zom
pushes button
realizes it is push and hold
zero visual indication of recording
sends two voice clips
cannot hear any sound in zom playback

single checkmark shield 

conversations receives nothing



...

friend is resigned that this works for secure texting 

friend continues passive aggressive griping, insisting me pay for normal texting instead


me ponders a friend upgrade

**Comment by loveuvfreight** [comment]
zom in example is 

https://github.com/zom/Zom-Android/releases/tag/15.0.3-beta-2

**Comment by n8fr8** [comment]
This should now be fixed with Omemo support.

**Comment by brighterness** [comment]
OMEMO SMP?  awesome

Is it challenge/response SMP?
