### ISSUE TITLE
'Last seen' XEP implementation

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#199]
- Parse out the ‘idle’ timestamp that is included with the presence updates (includes a time stamp of when the user interacted last)
- Do the same record keeping and broadcast out the last time he interacted with the app and set as away if the app has gone to the background for days

@chrisballinger correct or fill in details.

**Comment by chrisballinger** [comment]
We use XEP-0319: https://xmpp.org/extensions/xep-0319.html

```xml
<presence from='juliet@capulet.com/balcony'>
  <show>away</show>
  <idle xmlns='urn:xmpp:idle:1' since='1969-07-21T02:56:15Z'/>
</presence>
```

**Comment by n8fr8** [comment]
I am going to move this to the next sprint. It works for now on Android to some extent.
