### ISSUE TITLE
Match friend request buttons to iOS

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#200]
<img width="458" alt="screenshot 2017-03-27 15 37 00" src="https://cloud.githubusercontent.com/assets/1434597/24376757/a82427fe-1302-11e7-99e5-399e13684728.png">

Green background #449d44
Green border #398439

Red background #d9534f
Red border #d43f3a

The icons used are from FontAwesome. I've attached .svgs of the two we need. I know this goes against using material design icons, but in an effort to match iOS, I think it makes sense to use these. Also, I think they'll look better than material icons for the friend request because they have a heavier weight.

[icons-friend-request.zip](https://github.com/zom/Zom-Android/files/873717/icons-friend-request.zip)

**Comment by cstiens** [comment]
In addition, once a friend request is accepted from this view, they should be taken directly into a chat with that person.

**Comment by n8fr8** [comment]
I've made them as similar as I can for now
