### ISSUE TITLE
Group Chat: Delay in displaying members of the group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#201]
It took 2-3 minutes to show the members that were added to the group in the info view.

![delay-in-displaying-group-members](https://cloud.githubusercontent.com/assets/1434597/24521501/fd500670-1551-11e7-987e-6cd17b9aa423.png)

**Comment by n8fr8** [comment]
This is improved now... but it still may take until they join the room / accept the invite, to see them.
