### ISSUE TITLE
Group Chat: Un-invited people added to a group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#202]
Each ID after kimios was not invited to the group.

![uninvited-people-added-to-group](https://cloud.githubusercontent.com/assets/1434597/24521618/678026ec-1552-11e7-9008-edad31ee227e.png)

**Comment by n8fr8** [comment]
Those aren't people... they are kind of encryption ghost! True! Anyhow, this is related to a bug, but those aren't people.
