### ISSUE TITLE
dev_omemo: Do not build sessions with whole roster on startup

### ISSUE THREAD

**Issue by vanitasvitae** [zom/Zom-Android-XMPP#206]
The [XEP-0384](https://xmpp.org/extensions/xep-0384.html) recommends, that you only build a session when the user tries to send a message. Never build sessions without users consent.

I saw that Zom/dev_omemo builds sessions on startup which is bad performance wise. Just do it when the user starts typing a message/clicks the send button.

PS: I know, this is still heavily wip ;)

**Comment by n8fr8** [comment]
Thanks for the feedback. I don't think we build a session with the entire roster... I thought it was only with open conversations. I will look again, but definitely agree we don't want that amount of overhead.

We are also getting a handle on the difference between an OMEMO session and OTR session. Right now, the way we implement those in Zom is obviously wildly different and a bit of a frankenstein.

**Comment by mimi89999** [comment]
@n8fr8 Is there an IRC channel or MUC for Zom related discussion?

**Comment by vanitasvitae** [comment]
> I don't think we build a session with the entire roster...

I might be wrong, but I'm pretty sure that I saw Zom attempting to build sessions with 4 devices or so on startup.
