### ISSUE TITLE
dev_omemo: bug while checking for OMEMO support of resource

### ISSUE THREAD

**Issue by vanitasvitae** [zom/Zom-Android-XMPP#207]
```
04-12 21:12:38.617 13800 13959 W OMEMO   : error checking if resource supports omemo: test@server.tld/ChatSecureZom-d3dd4d85/ChatSecureZom-d3dd4d85
```
You appended the resource part to a fulljid (its twice after the jid). Thats why the method is failing.

**Comment by vanitasvitae** [comment]
Also: How do you handle multiple resources online at the same time? Is the class `Contact` per resource?

OMEMO uses quite a different model than OTR and deviceIDs are not related to resources, which makes it quite difficult to implement OTR alongside OMEMO I can imagine.

resourceSupportsOmemo is only useful if you want to determine, if the resource that is currently online supports OMEMO. Most implementations I saw so far do not use this to decide, whether to send an encrypted message or not, but rather to decide, whether to append the OMEMO encryption hint (your client seems not to support OMEMO...) to the message. 

I'd suggest, that if the user selects OMEMO as encryption method and there is at least one device known to support OMEMO (in the deviceList of the contact, not via resourceSupportsOmemo), than you encrypt the message, no matter, if the contacts resource supports OMEMO or not. Also, if the contact does not support OMEMO at all (no device published), than just don't present the user with OMEMO as an encryption option.

**Comment by mimi89999** [comment]
@n8fr8 https://github.com/zom/Zom-Android/blob/dev_omemo/app/src/main/java/org/awesomeapp/messenger/model/ChatSession.java#L153
`mParticipant.getAddress().getAddress()` is equal to `test@server.tld/ChatSecureZom-d3dd4d85`. Then we add resource a second time.

Is `mJid = JidCreate.from(mParticipant.getAddress().getBareAddress() + '/' + resource);` or `mJid = JidCreate.from(mJid.toString() + '/' + resource);` the correct way to do it?

**Comment by n8fr8** [comment]
I will fix the immediate bug, and then we can talk more about the larger issues.
