### ISSUE TITLE
Message from Android to iOS not sending when iOS is not open

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#214]
The message shows a single check when I send the message, and doesn’t go through until I open the zom app on iPhone. This same issue is happening when I send the message from iOS to iOS, but with slightly different side effects. https://github.com/zom/Zom-iOS/issues/281

Version 15.1.0-alpha-1

**Comment by n8fr8** [comment]
Isn't this correct behavior? We can't guarantee the iOS app will always immediately wake up or receive a push. Apple can throttle that. In this case, when you opened the app, the message was received, and receipt was sent back to sender.

**Comment by n8fr8** [comment]
Again, the queue by default fixes this.
