### ISSUE TITLE
App crashed when trying to send voice message

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#215]
Jodie's phone crashed when she tried to send voice message. After crashing, once she restarted, a message she’d sent before the voice message showed up under the voice message in the chat flow with a x-check.

@n8fr8 This issue is double-loaded. First, the crash when trying to send a voice message. Second, the occurrence of the x-check. I noted the second in the x-check issue #176 

version 15.1.0-alpha-1

**Comment by n8fr8** [comment]
x-check is now fixed. we queue all messages initially, as opposed to set them to "checked" by default.

As for the voice message crash, I am not sure.

**Comment by cstiens** [comment]
I haven't seen crashes with voice messages in the latest builds.
