### ISSUE TITLE
Need an easy way to hide file/photo/sticker icons

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#217]
They block incoming messages in the chat view. Currently you have to close out of the chat you’re in, then re-open it to get the options to hide.

**Comment by n8fr8** [comment]
I am confused by this. Can we get a screenshot?

**Comment by n8fr8** [comment]
You press the + to toggle them on and off.

**Comment by cstiens** [comment]
Got it. thanks.
