### ISSUE TITLE
Chat view forcing user to end of chat

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#219]
When she scrolls up in the chat view, it pushes her to the end of the message thread. It holds for a couple seconds but them jumps down. Note: the keyboard is open.

This issue is occurring on Jodie’s phone. It does not occur on other phones. 

version 15.1.0-alpha-1

**Comment by n8fr8** [comment]
Fixed now. If the user is scrolling back in messages, they won't be jumped down to the bottom when new messages or status ... comes in.
