### ISSUE TITLE
Photo not sent when contact’s app crashed

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#221]
TL tried to send Lala a photo just as Lhadon’s app crashed and it didn’t go through. TL saw it stuck at 63% the entire time.

version 15.1.0-alpha-1

**Comment by n8fr8** [comment]
This happens sometimes with OTRDATA. If one side crashes, it won't resume. The future OMEMO file transfer will address this.

**Comment by n8fr8** [comment]
OMEMO FTW!
