### ISSUE TITLE
Verification on Android - Chats are blocked when contact gets a new key

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#224]
Chats are blocked until the key for the new contact is updated and the user manually refreshes the session.
Test Android (user) to Android (contact with new key)

Conversation with Lala (Android) after Carrie (Android) got a new key:

- Lala tries to send carrie a message. Got the time clock.
- New keys didn’t refresh in the app immediately or after 3 minutes. 
- Lhadon closed then re-opened the app. New keys didn’t show.
- Lhadon force stopped the app and re-opened it and it showed only one key (which was the old key, omemo I think)
- We refreshed the session. And the keys refreshed. New key was shown on top.

@n8fr8 As we've discussed, this is the time to prompt users to verify the contact, but chats shouldn't be blocked if they haven't verified. Correct?

Related iOS issue: https://github.com/zom/Zom-iOS/issues/285

**Comment by n8fr8** [comment]
I think this is related to OMEMO, which does block messages if a key hasn't been set to trusted. Thanks for this very detailed error report. Exactly what I need to figure this out.
