### ISSUE TITLE
Chat switched from OMEMO to OTR messages

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#227]
I was chatting with Chris (who is using chatsecure). All of my messages were going through using OMEMO. After about 5 minutes, 16 text messages, 2 audio messages, it switched to using OTR.

It hasn't switched back to OMEMO yet. Also, it switched after a handful of text messages; not when or right after sending an audio message.

**Comment by chrisballinger** [comment]
Also I am still sending OMEMO messages, she just started replying with OTR
messages all of a suddden.

**Comment by mimi89999** [comment]
Try disabling chat encryption in settings.

**Comment by mimi89999** [comment]
I would say #203 or #209.

**Comment by mimi89999** [comment]
BTW, I am testing Zom with this JID: zom-test@lebihan.pl

If anybody wants...

**Comment by n8fr8** [comment]
We less aggressively init the OTR session now... only when the user wants to share media, or receives media, etc. We also have consistent support for OMEMO sending, and have updated the smack-omemo libraries. A new build is coming.
