### ISSUE TITLE
Show prompt to move to friend's new account based on V-card info in an individual chat

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#231]
https://cloud.githubusercontent.com/assets/1434597/25667292/b3eb22ce-2fe8-11e7-8cda-881ecdd8b09c.png

**Comment by n8fr8** [comment]
@chrisballinger @N-Pex is there a spec somewhere on what to add to the vcard?

**Comment by n8fr8** [comment]
This is in, I just can't seem to get the vcards to load with the forwarding address in the JABBERID field

**Comment by n8fr8** [comment]
This is technically in, if we get the new vcard from the contact.
