### ISSUE TITLE
System notification for Upgrading

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#236]
**Account expiring. Upgrade now.**
Your account is expiring in 'x' days. Open the app to upgrade.

Repeat daily at 11AM

iOS ticket is here: https://github.com/zom/Zom-iOS/issues/294 
We need to check the final copy. We had to make some tweaks.

**Comment by n8fr8** [comment]
I am now showing a notification to upgrade. It is too much work right now to do the timing each day, etc. I just show it when the devices boots and/or the app starts for the first time.
