### ISSUE TITLE
Send message to old friends

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#238]
When you migrate, send a message to your contacts from the old account telling them you've upgraded. 

"I’ve upgraded my account. Zom with me at name@home.zom.im."
button - "Chat Now."

Here's a link to the final copy for the entire migration flow: https://docs.google.com/document/d/1WIL1udV-OgR-UFOTDCjWWZILBA9AivFTsz64g9tmbV8/edit

**Comment by n8fr8** [comment]
@cstiens I think we're done with this, right? Is there something missing?

**Comment by cstiens** [comment]
Done!
