### ISSUE TITLE
Friend invite in chat (snackbar) diappears

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#239]
The snack bar disappears after 3-4 seconds, so if the user doesn't tap OK in time, they are unable to accept that friend request.

Friend requests are not showing up in the convo view, so the request gets lost after the snackbar disappears.

**Comment by n8fr8** [comment]
They should now show up in the Contacts list view, as any usual inbound friend request would

**Comment by cstiens** [comment]
Yes they are showing up in the Contacts list view. Snackbar still disappears from the new chat within 3-4seconds.

**Comment by cstiens** [comment]
I'm closing this because it's a duplicate of #250
