### ISSUE TITLE
Within a chat, it shows "your contact has stopped the encrypted chat”

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#242]
It showed shortly after the new friend request was accepted— not sure why it’s showing up. Both phones had working wifi.
![img_20170510_122821405_hdr](https://cloud.githubusercontent.com/assets/1434597/25915249/8c57adf6-3586-11e7-8834-5520c77d904c.jpg)

**Comment by n8fr8** [comment]
I've removed the display of this, as there isn't anything the user can do. They will see the message field revert to "Send a message" from "Send a private message"

**Comment by mimi89999** [comment]
BTW, if you disable screenshot protection in settings, you can take a screenshot from the device...
