### ISSUE TITLE
Improve button style on website

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#244]
Hey @n8fr8 I know this isn't Android specific, but... Any chance you could make the 'Add Friend' button on the website match the upgrade button style we have in the app (ie. yellow background with the Zom pink text). It would greatly improve the UX if that button stood out more. Thx.

![img_0265](https://cloud.githubusercontent.com/assets/1434597/25962569/df269d4a-3643-11e7-9bad-02b8cac680bf.PNG)

**Comment by n8fr8** [comment]
I made it nice and big and golden!

https://zom.im/i/#bWlja2UudGVzdDAwNTFAaG9tZS56b20uaW0_bT0x

**Comment by cstiens** [comment]
Thanks!
