### ISSUE TITLE
Archive view not showing archived

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#246]
In the convo archive, it's displaying the same list that's in the inbox.
In the friends archive, it's displaying the same list that's in active.

**Comment by mimi89999** [comment]
Also noticed it.

**Comment by n8fr8** [comment]
in progress

**Comment by n8fr8** [comment]
done!

**Comment by mimi89999** [comment]
I don't like that UI/UX for changing archive/chat from a dropdown menu from the archive button..

**Comment by n8fr8** [comment]
At some point it will be used to show blocked/banned and other types of filters, groups, etc, so the list makes more sense. Otherwise, the "Archive" button looked like an action for archiving, and not filtering.

Still.. thanks for the feedback and checking it out!

**Comment by mimi89999** [comment]
@n8fr8 So we will have both tabs and a drop-down menu?

**Comment by n8fr8** [comment]
We already have tabs in the UI, so we aren't going to have a second layer of tabs below that. 

Anyhow, for now, this is the solution, but happy to consider other options in the future for list filtering.

**Comment by cstiens** [comment]
Nothing is automatically archived. You can manually swipe to archive. But my pre-migrated chats aren't automatically archived and neither are any of my contacts. Pre-exisiting chats should be archived once a person migrates

**Comment by mimi89999** [comment]
We could have archive as a separate view accessible from the 3 dot menu. It has only 3 positions now...

**Comment by cstiens** [comment]
Nothing is automatically archived. You can manually swipe to archive. However, I don't see a different image to 'unarchive' the chat, making it difficult to 'unarchive'.  After I swipe the chat again (like I'm archiving) after about 10 seconds the chat will reappear in the 'active' view.

**Comment by cstiens** [comment]
We do see chats in the archive view
