### ISSUE TITLE
Add contact by Jabber ID: inviteBuddies invokes a null connection, thus inviting no buddies!

### ISSUE THREAD

**Issue by Gaffen** [zom/Zom-Android-XMPP#25]
Currently nothing happens (frontend wise) when you attempt to add a contact by their Jabber ID.

I suspect this is why:

In [AddContactActivity.java](https://github.com/zom/Zom-Android/blob/master/awesomeAppCore/src/main/java/org/awesomeapp/messenger/ui/AddContactActivity.java#L414), the provider ID and account ID are not set, thus not opening a connection.

Addendum, mAccountId and mProviderId should be set and passed back in the extra to launch the chat window after the contact has been added.

[I have created a patch to fix this issue](https://gist.github.com/Gaffen/247806bce88d39120602)

**Comment by n8fr8** [comment]
This should be fixed now. We are using the same AddContactAsyncTask as all the other invite processes use.

Thanks for your patch!
