### ISSUE TITLE
Add friend snack bar disappearing feels unpredictable

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#250]
The add friend snackbar appears within a chat for a few seconds, then disappears. It makes me feel a bit anxious and out of control as a user. Could we keep it there until the user taps okay?

**Comment by n8fr8** [comment]
There should be a way to cancel it. I guess if I properly implemented the header display for waiting for approval and/or incoming approval, then we don't need the snackbar.

**Comment by n8fr8** [comment]
Isn't this a duplicate of #239 ?

**Comment by n8fr8** [comment]
It will stay open now until they confirm.

**Comment by cstiens** [comment]
The snackbar is still disappearing. If I choose not to accept the friend and exit the chat. Once I reopen a chat with the friend the snackbar appears again. Yes, this is a duplicate of #239. And the friend request is available in the Contacts view.

**Comment by n8fr8** [comment]
I believe I have set the snackbar time to "indefinite" now

**Comment by cstiens** [comment]
Stays up for about 10seconds. You don't have to accept in order to chat. Also, if you don't add them and reopen the friend request the snackbar will appear again.

**Comment by n8fr8** [comment]
Can we close this since it is a duplicate of #239 ?

**Comment by n8fr8** [comment]
It should now stay up permanently.

**Comment by cstiens** [comment]
Hey Nate, the snackbar seems to be gone completely in build 15.1.0-RC-2. Was that intentional?

**Comment by n8fr8** [comment]
Uh, no... Strange. I definitely had it showing up when I tested adding a new inbound friend request. Are you seeing the check/X prompt for the friend, or are they just being automatically added?

**Comment by cstiens** [comment]
> Are you seeing the check/X prompt for the friend, or are they just being automatically added?

The check / x friend request is still showing up. They are not automatically added.
