### ISSUE TITLE
Add migrate option in account settings

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#252]
It would be nice to add 'migrate account' option in account settings.

**Comment by n8fr8** [comment]
It is already there, but hidden under the 3 dot setting. Go to "My Accounts" and then select an account, then tap the 3 dots to find the Migrate option.

**Comment by n8fr8** [comment]
We could/should find a way to possibly make it more apparent, but I think for now it is best to be hidden. We mostly want, in the future, to think about how to prompt the user to migrate if we think their server is blocked.

**Comment by cstiens** [comment]
Sounds good. I'll close this one.
