### ISSUE TITLE
OMEMO Gajim and Zom

### ISSUE THREAD

**Issue by Simon0Harms** [zom/Zom-Android-XMPP#259]
It  looks like gajim didn't get the information that the client can use omemo.

The other only have the zom.im app and the gajim client try to encrypt otr instead of omemo.

€dit:
The Omemo Option is in my conversations Client greyed out for this contact.

**Comment by n8fr8** [comment]
Okay thanks! We are still getting the Omemo features working properly, and will default to OTR if it is available.

**Comment by Simon0Harms** [comment]
Ok, how can i get informed, that zom is really ready for omemo?
I want to recommend it everyone when omemo is ready

**Comment by JokerGermany** [comment]
Ok, how can i get informed, that zom is really ready for omemo?
I want to recommend it everyone when omemo is ready

**Comment by n8fr8** [comment]
Zom should fully work now with Omemo and Gajim. It has been tested with Conversations, ChatSecure and other apps.

**Comment by githubboy1** [comment]
i have tried this on my own for testing.
i have create a zom account on smartphone (testman@nang.zom.im)
And on Gajim i use TonsOfFun@Jabber.hot-chilli.net

But its not connecting with each other.
so it doesn't work anymore or is something else going on?
