### ISSUE TITLE
Starting chat sessions

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#260]
- queue messages until approved
- once person approves you, fetch omemo keys
- initiate omemo session
- then do otr session

Here's the iOS ticket that addresses this—https://github.com/zom/Zom-iOS/issues/337

**Comment by cstiens** [comment]
@n8fr8 can this one be closed? It seems that we're past it, and working out smaller issues associated with OMEMO.

**Comment by n8fr8** [comment]
Yup!
