### ISSUE TITLE
Archive/Unarchive view filter switching is buggy

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#262]
Sometimes it doesn't switch the filter list view

**Comment by n8fr8** [comment]
Seems stable now.

**Comment by tiffrobo** [comment]
Yep! Seems stable. 

Device: Moto E
OS: Android 5.1

Device: Moto G play
OS: Android 6.0.1


Device: Moto X 
OS: Android 5.1

App version: 15.4.0-beta-1
