### ISSUE TITLE
If OMEMO fails, we should fail over to try OTR

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#267]
Currently, if OMEMO is possible, and fails, we just queue the message to try again. Instead, we should see if OTR is possible, and instead send it that way.

**Comment by chrisballinger** [comment]
I think automatically switching to a legacy encryption method is
potentially dangerous and should be avoided.

**Comment by n8fr8** [comment]
Agreed, bad idea!
