### ISSUE TITLE
HTTP Upload not working

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#268]
&lt;iq to='home.zom.im' id='kW3j0-140' type='get'&gt;&lt;request xmlns='urn:xmpp:http:upload:0'&gt;&lt;filename&gt;871507918.jpg&lt;/filename&gt;&lt;size&gt;71893&lt;/size&gt;&lt;content-type&gt;application/octet-stream&lt;/content-type&gt;&lt;/request&gt;&lt;/iq&gt;
07-03 13:33:14.646 28421-28612/org.awesomeapp.messenger.debug D/SMACK: RECV (0): &lt;iq id='kW3j0-140' type='error' to='nathantest.5ee1a6cb@home.zom.im/ChatSecureZom-a2fea7b4' from='home.zom.im'&gt;&lt;error type='modify'&gt;&lt;bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/&gt;&lt;text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'&gt;Invalid filename&lt;/text&gt;&lt;/error&gt;&lt;/iq&gt;
07-03 13:33:14.652 28421-28421/org.awesomeapp.messenger.debug E/ZomXMPP: error getting upload slot
                                                                         org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from home.zom.im: XMPPError: bad-request - modify

<iq to='home.zom.im' id='kW3j0-140' type='get'><request xmlns='urn:xmpp:http:upload:0'><filename>871507918.jpg</filename><size>71893</size><content-type>application/octet-stream</content-type></request></iq>
07-03 13:33:14.646 28421-28612/org.awesomeapp.messenger.debug D/SMACK: RECV (0): <iq id='kW3j0-140' type='error' to='nathantest.5ee1a6cb@home.zom.im/ChatSecureZom-a2fea7b4' from='home.zom.im'><error type='modify'><bad-request xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/><text xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'>Invalid filename</text></error></iq>
07-03 13:33:14.652 28421-28421/org.awesomeapp.messenger.debug E/ZomXMPP: error getting upload slot
                                                                         org.jivesoftware.smack.XMPPException$XMPPErrorException: XMPP error reply received from home.zom.im: XMPPError: bad-request - modify

**Comment by n8fr8** [comment]
@chrisballinger @flowdalic any thoughts on this?

**Comment by Flowdalic** [comment]
While I wouldn't bet on it, I don't think that's a client (library) issue. It appears that for some reason, your http upload service doesn't like the filename. Maybe because its basename is all numeric? Just guessing.

**Comment by n8fr8** [comment]
Check the pull request here: https://github.com/igniterealtime/Smack/pull/151
