### ISSUE TITLE
Zom App ist called ChatSecure since the last googleplay update 

### ISSUE THREAD

**Issue by Simon0Harms** [zom/Zom-Android-XMPP#273]
![screenshot_2017-07-19-18-35-19](https://user-images.githubusercontent.com/10880193/28378637-298cb06a-6cb1-11e7-945d-60affae851d4.png)

**Comment by n8fr8** [comment]
In what language are you running the app?

**Comment by Simon0Harms** [comment]
German, it is fixed with your commit, you are right.

PS:
Will my translation be implemented sometime?
https://github.com/zom/Zom-Android/pull/265

**Comment by n8fr8** [comment]
Yes
