### ISSUE TITLE
Nickname not set from the user input

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#280]
New account nicknames should be set from what the user types as their nickname, and not what is autogenerated for the jabberid

**Comment by cstiens** [comment]
When we tested this, it was buggy. We created accounts 3 times. Out of those, it worked correctly twice. But, in one case, it showed the nickname with the auto-generated numbers.

**Comment by cstiens** [comment]
This works now with all the latest improvements!
