### ISSUE TITLE
UI to edit group name

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#290]

**Comment by cstiens** [comment]
@N-Pex Here's the UI:

<img width="719" alt="screenshot 2017-09-07 14 23 31" src="https://user-images.githubusercontent.com/1434597/30181258-4638bf1c-93d8-11e7-84a5-351ab84c9012.png">

Once the user taps the edit icon, show the same UI we show for editing a username. Side note: I'd like to improve the 'new name' view in the future, but let's stick with it for now.

**Comment by N-Pex** [comment]
Does this edit the room subject (which is/can be restricted to certain users/roles) or just what we locally call the room on the client?

@n8fr8 Also, from what I can see in the specs, we can't tell when a room was created and by whom(?). The closest thing is that we can display those that are currently marked as role "owner". Maybe there's a possibility to use custom fields/extend the spec for this?

**Comment by N-Pex** [comment]
Still needs more work on disabling/enabling the edit option based on room role/config, but for now it is assumed that all users can edit the subject.
