### ISSUE TITLE
OMEMO keys getting lost for existing friends

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#294]
@n8fr8 I've been running into the issue of keys disappearing quite frequently lately. 
Also, we're trying out a new format for reporting bugs. I've used it below—

**What did you do?** I tried to send a message to the android from the iphone. 

**What did you expect to see?** I expected the message to go through.

**What did you see instead?** I only got one check, so I opened Zom on android and opened the chat with the iphone. Nothing had come through. 

**How did you resolve the issue?** So, I opened the info view on android and saw that there were no keys for the iphone contact. I tapped verify. I ran into issue #293. The app crashed, but it did verify the contact. When I reopened Zom on android, the message from iphone had come through.

**Device model, OS and Version** Galaxy S7
**Zom Build** Version 15.3.0-alpha-1

This issue may be related to #266

**Comment by n8fr8** [comment]
I believe this was related to server instability issue. Let's keep an eye out for this again, but nothing to do right now.

**Comment by n8fr8** [comment]
This shouldn't be happening anymore.
