### ISSUE TITLE
If you sign out and sign back in, you’re not a part of the group anymore

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#297]
We need to re-establish the connection.

**Comment by n8fr8** [comment]
Fixed in 15.3 alpha 3

**Comment by cstiens** [comment]
Works! 
Chat history possible regression. When I was signed out for a week I and signed back in. I didn't receive any of the chat history sent during my 'logged out' time. Only fetching the chat history of the day you sign bak in. Will do some more testing to determine if this happened because I was signed out/inactive for a week.
