### ISSUE TITLE
Sharing photo from phone gallery fails to send

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-Android-XMPP#303]
Here are the steps I took:
- I am in my phones photo gallery. Chose a specific photo I want to share. Select share. Zom icon appears.

- Tap Zom icon. Opens Zom and asks to choose a friend. 

- Choose a friend to send the photo to. Zom closes. Lands on photo I sent in the gallery. 

- No idea what happened. Did I send a photo? 

- If I open Zom. There is no indication that I've recently sent a new chat (sent the photo). Open a chat with the contact I sent the photo to. I see the photo in the thread of conversation, but with one check. So the photo did not send. 

Device and OS: Android 6.0.1 MotoX (Though this isn't specific to the device. It's happening on other Android phones as well)
App Build: Version 15.3.0-alpha-2

**Comment by tiffrobo** [comment]
I also experienced this issue when sharing an audio file from my downloads folder.

**Comment by n8fr8** [comment]
Should be fixed now, at least sending to one. Still debugging sending to multiple.
