### ISSUE TITLE
Make new/unread messages bold in convo view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#304]
When I get a new message, I get an Android notification. If I tap on the notification, it takes me right to that chat. Though, if I have multiple new messages and just open Zom to the convo screen, I can't tell which messages are new and/or unread. On iOS, we make the sender bold. Our display on Android is slightly different. i.e. The message summary is more prominent. So, I think we should make the message snippet bold on Android if it's unread.

![img_0387](https://user-images.githubusercontent.com/1434597/30218946-26b8bfae-9480-11e7-8d81-f8d0e6be6663.JPG)

**Comment by N-Pex** [comment]
@n8fr8 I guess we can't currently tell that we have unread messages, since ChatSessionAdapter.markAsRead does not reset LAST_UNREAD_MESSAGE to null. Maybe we should add a new column?

**Comment by n8fr8** [comment]
Yes we could do that. "HasUnread" or something along those lines.

**Comment by N-Pex** [comment]
I added a column LAST_READ_DATE for greater flexibility.

@cstiens I am not sure this is clear enough, it's pretty hard to see what's bold and not currently. Maybe we should do something with colors instead?

**Comment by cstiens** [comment]
@N-Pex What if, rather than making the message snippet bold, we made the sender name bold and black (like iOS). I also noticed that if the latest message is a picture, we can't indicate that it's new if we bold the message. In the next sprint, I want to update the fonts on Android, so I think that will help with legibility also.

**Comment by N-Pex** [comment]
Ok, yes, that does look better.

**Comment by cstiens** [comment]
Working! It would be nice now to have the content of the message less bold. Currently looks like bold on bold in my inbox. Maybe when the new fonts are implemented it will help.
