### ISSUE TITLE
Adding an iOS friend to a pre-existing group creates a new ‘fake’ group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#309]
There’s a pre-existing group. On Android, I selected ‘add a friend’. I chose an iOS friend. Currently, Android doesn’t show the members so I don’t know if they were added. But, the iOS contact that was added was added to a new group (with a new name) auto-created as a duplicate of the original group. It has all of the same group members. 
But, when we compared the member list with another iOS group info view, the last contact added was not a part of the original group. 
*I call it ‘fake’ because the group is only between the person that added the new iOS contact and the new iOS contact. The member list shows that everyone from the original group is a part of it, but only the 2 people see the group and the chats.

**Comment by n8fr8** [comment]
Is this still happening?

**Comment by cstiens** [comment]
Once there's a release out with everyone as an admin, we'll test it again. It seems to happen if someone that didn't create the group tries to add someone.

**Comment by cstiens** [comment]
@n8fr8 If the creator of the group adds someone, this does not happen. I think we were having this issue when non-admin were adding people to the group. But, if they can't do that, then we would remove that from their UI and we shouldn't have this issue.

**Comment by cstiens** [comment]
iOS members still have the option to add members to an Android created group, which is a bug. But since it's not fixed in the build we have, we're testing this. So if an iOS member tries to add another Android phone to the group, here's what happens:
- Select 'add zom friend'
- Opens 'Choose friend' view
- When you tap on the person, it takes you back to the group info view but does not add the person
