### ISSUE TITLE
In iOS created group, iPhones can resume group chat, but Android cannot

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-Android-XMPP#311]
An iOS created a group consisting of iOS and Android contacts. Everyone in the group could chat. Three days later, the group resumed chatting. Android contacts were not able to send or receive group messages. 

Here are the steps I took:

-An existing iOS created group began chatting and the Android phones in the group did not receive any of the messages or push notifications.

- An Android phone in the group tried sending the group a message. The chats do not go through. 

- Repeated the steps with another Android phone in the group. Chats did not go through.

- Checked and all phones in group chat had each others keys. 

- Android can send individual messages to other people in the group (on iPhone and Android)

Device OS: Android 6.0.1
Device: Moto G play
App version, build number: 15.3.0-alpha-2

**Comment by n8fr8** [comment]
fixed in alpha 3
