### ISSUE TITLE
Replace audio player with "Audio Wife"

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#312]
Better UI, time is display, scrubbing, etc:

https://github.com/jaydeepw/audio-wife#including-in-your-project

**Comment by N-Pex** [comment]
Seems easy enough. @cstiens Do you have any design ideas for how this could look?

**Comment by cstiens** [comment]
I can. :)

**Comment by n8fr8** [comment]
There is a pretty decent default player view. I've done the first pass on incorporating this, and will have it in the build for Sunday.

**Comment by n8fr8** [comment]
![screenshot_20171121-161339](https://user-images.githubusercontent.com/30851/33097098-0a57069a-ced7-11e7-9092-6ccccd559dba.png)

**Comment by cstiens** [comment]
This is a great start! Here's a snapshot of an idea for the visual design—

- The first audio file represents a file that is played.
- The second, one that is playing.
- The third, one that is new and hasn't been played.

<img width="376" alt="screenshot 2017-11-21 15 18 01" src="https://user-images.githubusercontent.com/1434597/33097346-7780ba20-cecf-11e7-9461-1d6dfc69fb01.png">
