### ISSUE TITLE
Links sent from iOS do not display on Android phones in group chat

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#316]
I copied a link for a webpage in safari and pasted it into a group chat from my iphone. The other iphones in the group received it, but the Android phones get nothing.

**Comment by n8fr8** [comment]
I just tried to reproduce this and cannot. If you can do so again, please share the exact link you used here.

**Comment by cstiens** [comment]
Sure. I just did it again and had the same results. The link is https://www.rottentomatoes.com/m/life_2017
