### ISSUE TITLE
Enable moderator status for everyone in the group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#319]
As we discussed on the scrum, this will allow everyone in the group to see the member list and add members.

**Comment by n8fr8** [comment]
I think this is already done. I am actually enabling "Admin" status, since it can be done when they are invited, and doesn't require me to wait untli they actually join the room.

**Comment by N-Pex** [comment]
Yup, just building version 94 os iOS which mimics this - gives them all admin affiliation. Hopefully in a TestFlight near you soon...
