### ISSUE TITLE
Archiving group chats not working

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#321]
When I archive a group chat I no longer see it in my convos view. 
When someone sends a new message I receive the notification and the group reappears in my convo view. 

App version: 15.3.0-alpah-5

**Comment by n8fr8** [comment]
1) I think the archive UI is a bit borked right now. Looking into it.

2) I don't think we consider "archived groups" when we were implemented the archive feature.

So.... will need to decide of this is a blocker or not for current release, but must get to it soon regardless.

**Comment by n8fr8** [comment]
Actually I think this a feature right? Archiving a conversation doesn't mean hide it, it means, take it out of my main convo list view until there is a new message available.

This is the same behavior with a one on one chat too i believe. If a new message is sent by the remote party, it should move to the front.

This is different than if you archive the Contact themselves.

**Comment by cstiens** [comment]
Link to iOS ticket: https://github.com/zom/Zom-iOS/issues/411

I think we need to decide what the desirable behavior is and sync that on both platforms. Currently, the behavior is slightly different.
