### ISSUE TITLE
Update pending approval UI

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#323]

**Comment by cstiens** [comment]
Please see the mockup below. I made the image smaller and grayscale. I've attached the .png. The refresh icon is from the material library https://material.io/icons/#ic_refresh. Refreshing should send a reapprove subscription method.

<img width="371" alt="screenshot 2017-09-15 15 05 24" src="https://user-images.githubusercontent.com/1434597/30501163-ee06d946-9a26-11e7-94d7-02e0be6103c8.png">

![15biscuit50](https://user-images.githubusercontent.com/1434597/30501323-a1a0d772-9a27-11e7-8d10-b25fc542d08f.png)

**Comment by N-Pex** [comment]
Fixed in 95.
