### ISSUE TITLE
QR code is distorted

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#334]
@n8fr8 See screenshot. I believe this was introduced in the latest build, or whenever the pink background was added behind the bottom QR code.

It shows up this way on 2 different devices.

![screenshot_20170925-115155](https://user-images.githubusercontent.com/1434597/30820896-01882082-a1e9-11e7-8b15-75129d295faf.png)

**Comment by n8fr8** [comment]
The top image is an iPhone, tho, isn't it?

What do you mean by distorted?

The change made was to generate the QR code at a lower resolution. Is that it is blurry?
