### ISSUE TITLE
Bug with muting group notifications

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#337]
Here's what is happening:

- I am in group chat, tap info page, I change selection to 'Mute Notifications' and tap back to the group chat view. Then I tap back again (ie leaving the group chat view).

- Someone sends a message to the group.

- I reopen the group chat and tap the info tab. My selection is changed back to 'Mute Notifications' instead of 'Turn Notifications On'.

- Sometimes the notifications come through un-muted. Other times they stay muted.

App version: 15.3.0-alpha-5 and beta 2

**Comment by tiffrobo** [comment]
Muting notifications for group chat seems to only be working for text messages and links. 

If an audio or photo message is sent to the group chat, you receive a notification.
Notifications are still shown as muted in group chat settings.


Devices: Moto X, Moto G Play, Samsung Galaxay S7 
App version and build: 15.3.3. beta-9

**Comment by cstiens** [comment]
Fixed!
