### ISSUE TITLE
Incorrect response to multiple friend requests

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#339]
When a remote user "waiting for approval" presses the refresh button, the user is automatically approved by Android without the receiving user having control.

**Comment by cstiens** [comment]
Related issue and testing results on the iOS tracker: https://github.com/zom/Zom-iOS/issues/432

**Comment by tiffrobo** [comment]
When a user sends a new friend request to someone and the user who is "waiting for approval" presses the refresh button, they receive a notification saying "you and so-and-so are now friends". You can open a chat with the friend, but you never exchange keys and cannot chat. The 'new friend' has not accepted or refused your request. 

We tested and reproduced this bug. 

Devices: Moto X, Moto G Play and Samsung Galaxy S7
Build and App version: 15.3. beta 8

**Comment by n8fr8** [comment]
The "refresh" button now just resubmits the friend request, without changing the local status.

**Comment by cstiens** [comment]
@n8fr8 This issue is fixed, but there's a related issue—when you tap on the friend invite notification, it opens a chat with that person and adds them as a contact. #360

**Comment by cstiens** [comment]
Looks like these are all taken care of now!
