### ISSUE TITLE
Received double checks, but friend didn't receive the chats

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#341]
@n8fr8 This is the issue between Jodie and I. I sent her 2 messages. Initially I had a single check. When I opened the chat the next day, it showed a double check. Though, when I talked with her in person, she still hadn't received those messages. 

Jodie did have to restart her phone at one point the day I sent the messages.

**Comment by n8fr8** [comment]
I have made a number of small changes to address this, but am not sure 100% of when it happens. I can't reliably reproduce.
