### ISSUE TITLE
Zom crashes when user selects 'scan' from 'add friend' view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#342]
**Android build**
Beta 5

**Devices**
Samsung Galaxy S7
MotoX

**Comment by n8fr8** [comment]
Any way you can get the crash log for this? Do you have adb or another crash log tool setup on a desktop or on the phone itself?

**Comment by cstiens** [comment]
> Do you have adb or another crash log tool setup on a desktop or on the phone itself?

No. @n8fr8 Is there an app you suggest? We could install it and get the log.
