### ISSUE TITLE
Regression in fetching group chat history

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#346]
If you join the day after a group is created or rejoin, you only get the message history for things sent that day, rather than the last 20 messages. Same for iOS and Android.

This was working correctly prior to build 101 iOS and beta 6 Android.

@n8fr8 did anything change?

**Comment by n8fr8** [comment]
I am progress on this in the last build, and now directly request older messages when you reconnect to a group

**Comment by tiffrobo** [comment]
Still only receive the days post when joining or rejoining an existing group. 
And today when testing one Android device who was newly added to an already existing group, only received the posts made by iOS members from today.
