### ISSUE TITLE
Rejecting a friend request allows the contact to show up as a friend. 

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-Android-XMPP#352]
When a user sends a friend request and the receiving user 'rejects' or taps the 'X', the contact appears in the receiving user's friends list. 
They can start a chat, but only receive a single check. No keys are exchanged. 

The sending user's "waiting for your friend to approve you" goes away and they are able to send chats. Although, no keys are exchanged so no messages go through. 

Keys are exchanged when someone verifies the other contact.

Devices: Moto X and Moto G Play
App version and build: 15.3. beta 8

**Comment by n8fr8** [comment]
The user should now continue to see the "Waiting..." message and also in the contact list, it will display this message "Sorry, you are blocked by the user." which we already had in translated strings.
