### ISSUE TITLE
Adding a photo avatar to my profile during Zom account setup

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-Android-XMPP#353]
**1. Crashes the App**

When I created a new account on a fresh install I chose to add a photo as my avatar. I took a picture and accepted the picture. Once I tapped the checkmark to accept the picture the app crashed. 

I reinstalled the app and created a new account and again tried adding a photo avatar. The app crashed again. 
Both times, when I reopen the app it opens to the convo view. 

Device: Moto X 
App Version and build: 15.3.beta-8

**2. Doesn't Work**

When I created a new account on a fresh install I chose to add a photo as my avatar. I took a picture and accepted the picture. When I tapped the checkmark, the photo disappears and the app is in convo view. I don't know if it worked. If you look at the me tab, there is no photo avatar for my profile. 

I reinstalled the app and created a new account and again tried to add a photo avatar. The same thing happened again. 

Device: Moto G Play
App Version and build: 15.3.beta-8

**Comment by cstiens** [comment]
Notes from @tiffrobo —

It still isn't working. On the black phone (motoG) the app never crashed, but the photo never stuck. On the white phone (motoX) the app crashed every time i tried to choose a new photo avatar.
 
Setup: When I tested I performed all the steps, but the photo doesn't stick. Once you take it and tap check mark, it goes back to the account setup screen so you don't know what happened. In fact, I couldn't get the photo avatar to work at all (stick).

**Comment by n8fr8** [comment]
Just to confirm, this is only when you take a new picture as your avatar? does it work fine if you select an existing image?

**Comment by tiffrobo** [comment]
@n8fr8 I just tested this again and the app crashed both when taking a new photo for my avatar and also when choosing an existing image from my gallery.

However, it didn't always crash when I chose an existing photo, it did **always** crash if I took a new photo. 

Device: motoX
OS: 5.1
App Version: 15.3.2 beta 1

**Comment by cstiens** [comment]
I just tested this on the motox. When I chose to 'take a picture' it worked just fine. 

I tested again on a motog4, and had a small issue— I'm closing this ticket and opening a separate one for it. The app is not crashing now so that's awesome!!
