### ISSUE TITLE
Adding a blocked contact to a group chat crashes the app.

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-Android-XMPP#356]
I was creating a group and tapped on a blocked contact and it crashed the app. Reproduced this crash multiple times. 

Device: Moto G Play and Moto X
App version and build: 15.3 RC 1

**Comment by cstiens** [comment]
In build RC 2, the app still crashes if you try to add a blocked contact to a group. @n8fr8 Can we filter out contacts that are blocked from this list, so they're not even an option?

**Comment by cstiens** [comment]
Blocked contacts are no longer shown as an option for adding them to group chats. Fixed.
