### ISSUE TITLE
Hitting refresh in group chat changes the group name

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-Android-XMPP#359]
In group chat we currently see "waiting for your friend" and the refresh button. If you tap the refresh button then tap the back button, the group name changes to numbers and letters. 

I retested this bug and reproduced it several times. 
**Only happening on Android created groups.** 

Devices: Moto X, Moto G Play
App version and build: 15.3 RC 1

**Comment by n8fr8** [comment]
The "waiting" dialog should never show in a group chat.... working on fixing that.
