### ISSUE TITLE
Tapping on a friend invitation notification of a blocked contact opens a chat

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-Android-XMPP#360]
If you reject a friend request and tap on the friend invitation notification that came with the initial friend invite, a chat opens. You can send a chat. Receive single checks. 

I saw two different views when the chat opens. 
View 1:
One chat opens with "waiting for your friend" and you can still send a chat. You receive a single check.

![screenshot_2017-10-12-17-53-14](https://user-images.githubusercontent.com/30634981/31522995-7cd70f92-af76-11e7-8107-24733775431c.png)

View 2:
The chat opens with no pending approval. You can send a chat and you receive a single check. 

![screenshot_20171012-145415](https://user-images.githubusercontent.com/30634981/31522578-2de4325e-af74-11e7-918f-ecd272d12751.png)

The rejected contact sees "Sorry, you have been blocked" They can open a chat with you, but they see "waiting for your friend" They can send a chat but only get single checks. 

Devices: Moto X and Moto G Play
App Version and build: 15.3 RC 1

**Comment by n8fr8** [comment]
The fix should now clear the notification when you decline/block the contact.

**Comment by cstiens** [comment]
Done. Thanks!
