### ISSUE TITLE
Undo archiving of buddies doesn't work

### ISSUE THREAD

**Issue by abeluck** [zom/Zom-Android-XMPP#372]
In the Zom app I regularly accidentally archive buddies when swiping between the tabs. That in and of it self is a UX bug.

But worse, once I do that I get the black bar that allows me to undo it, but clicking the undo button doesn't do anything.

Also, once I've archived buddies, how do I see them again? (especially if I also accidentally archived the chat with them!)

**Comment by N-Pex** [comment]
You can un-archive them again by selecting the "filter" icon top right on the Zom | Friends screen, selecting archive (which will show you archived buddies) and then swiping them again there.

As for the "undo" not working, I'll have a look.

**Comment by abeluck** [comment]
🎆  Did not even see that filter button. Thanks!

**Comment by N-Pex** [comment]
Great thanks, I fixed the "undo" in the snack bar as well, so that'll work once my PR is merged.

**Comment by cstiens** [comment]
Working!
