### ISSUE TITLE
Turn off auto-correct and spell check in account view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#381]
@n8fr8 is this something we have control over? When A was creating a new account on a chinese phone, it would auto correct im to i'm. We haven't seen this happen on our motox, motog or galaxy devices.

Device: Iku C40L (costs $50; very small screen)
Android 6.0

**Comment by n8fr8** [comment]
You mean when the user enters a new username, to turn of autocorrect / suggestions?

**Comment by tiffrobo** [comment]
@abeluck This was the issue you were having on your Chinese phone. Will you test it and let us know if it does not auto-correct now?

**Comment by abeluck** [comment]
@tiffrobo  Sorry just saw this ticket. I've tested and it works!
