### ISSUE TITLE
Hitting the 'Skip' button from the add friend view in onboarding takes you back to the very first onboard view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#382]
Hitting the 'Skip' from the add friend view in onboarding ("you’re almost ready to zom"), takes you back to the very first onboard view, then takes you through the steps to create a new account.

‘A' force quit the app, then reopened it,  and it opened to the convo view logged in to the account he originally created.

**Comment by n8fr8** [comment]
I can't reproduce this.

**Comment by cstiens** [comment]
Tested this, and it's no longer happening.
