### ISSUE TITLE
Add ability to delete a photo from the full screen photo view

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#387]
We can add a trash can to the action bar before the send and share options. We should have the user confirm this action since it can't be undone. A modal to confirm the action is standard, but maybe we can do something more more subtle. I'll think about it.

Note: As on iOS, deleting a photo would remove it from local storage.

**Comment by cstiens** [comment]
* This also affects the zomkyi script, so it's marked as 'high'

**Comment by cstiens** [comment]
We need to test deleting a photo from the full screen view when it's opened from a chat and from the photo gallery.

**Comment by tiffrobo** [comment]
Deleting photos from the chat works (deletes from photo stream and chat view)
Deleting photos from the photo gallery/stream is not working at all.

Device: Moto E
OS: Android 5.1

Device: Moto G play
OS: Android 6.0.1

Device: Moto X 
OS: Android 5.1

App version: 15.4.0-beta-1

**Comment by tiffrobo** [comment]
**Group Chat:**
- Deleting photos from group chat crashes the app. 
- The app opens on Zom Welcome page. I force quit and restart the app to open zom in my account. App briefly shows signing in...
- Does not delete the photo.

**Single Chat:**

- Deleting photos from single chat crashes the app.
- The app opens on Zom Welcome page. I force quit and restart the app to open zom in my account. App briefly shows signing in...
- The photo was deleted from the chat history and photostream. 

**Photo Stream:**

- Deleting a photo from the photo stream deletes it. 
- In a few cases, it deleted it from everywhere (chat history and photo stream).

Device: Moto G play
OS: Android 6.0.1
Device: Moto X 
OS: Android 5.1
App version: Android 15.4 beta 2

**Comment by n8fr8** [comment]
repro'd and fixed the crash in group and chat.

if you delete from photo stream, it will delete from everywhere that particularly copy of the photo appeared, so all the chats, etc.

**Comment by tiffrobo** [comment]
- Deleting a photo from full screen appears to be working everywhere now. I haven't seen the app crash. 
- In a few cases, it took a bit for it to delete from the single chat, but does work.

-Suggestion: If the photo is the last message sent and you delete it from the chat it would be nice to show the 'new' last message when one exits the chat view and switches to convo view. 
Currently, in convo view under the contact name, it shows a blank space where the photo was. 

Device: Moto E
OS: Android 5.1

Device: Moto G play
OS: Android 6.0.1

Device: Moto X 
OS: Android 5.1

Build: 15.4.0 RC 1

**Comment by cstiens** [comment]
I filed a separate ticket the T's suggested enhancement: https://github.com/zom/Zom-Android/issues/434
