### ISSUE TITLE
certificate expire 

### ISSUE THREAD

**Issue by gabriel-tessier** [zom/Zom-Android-XMPP#389]
Hi, one certificate expire and there's an infinite pop-up asking to cancel or allow the connection...  Somebody forget to renew it?
Or there's something I need to do?
Thanks for any help.

**Comment by n8fr8** [comment]
Apologies, there was work being done on servers, and indeed the new certificate didn't get deployed. 

All better now?

**Comment by gabriel-tessier** [comment]
Yes! 👍 
Thanks!
