### ISSUE TITLE
Add audio icon to attachment icons

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#392]
To increase the awareness of the ability to share audio files

**Comment by cstiens** [comment]
Red hex is: FF4444 (icon is 'mic' from material design: https://material.io/icons/#ic_mic)
Blue Doc hex is: 4A90E2

<img width="454" alt="screenshot 2018-01-19 13 55 25" src="https://user-images.githubusercontent.com/1434597/35168975-6efc34a4-fd20-11e7-9019-778fcfc20fe5.png">

* I'm marking this as high because it affects the zomkyi script

**Comment by n8fr8** [comment]
I used a music not icon to distinguish it from the mic recording

**Comment by cstiens** [comment]
Great! Good call.

**Comment by cstiens** [comment]
@n8fr8 Is there any way to filter the options in the gallery view to only show audio files?

**Comment by n8fr8** [comment]
yeah, it should be doing the filtering now. It launches the file/document chooser, and limits it by mime to audio/*

**Comment by cstiens** [comment]
Ok. On my Samsung phone, it brought up the downloads, which showed a mix of .apk files and audio. We'll test on some moto phones though too.

**Comment by n8fr8** [comment]
ah... is there a left drawer menu that has an "Audio" option? I think unless we implement our own file browser we are at the mercy of whatever the phone itself provides.

**Comment by cstiens** [comment]
> ah... is there a left drawer menu that has an "Audio" option?

Yes. And when you open it you see sub-folders. 

>  I think unless we implement our own file browser we are at the mercy of whatever the phone itself provides.

Probably so. Especially with so many different default gallery browsers.
