### ISSUE TITLE
Improve logging of sign-in/connection failures

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#396]
signing in can hang... hard to tell if the client or server.

**Comment by cstiens** [comment]
@n8fr8 For a couple days, when I was in the office (connected to wifi and data) my zom would say it was signing in every time I opened the app. 2-3 of the times I opened my account view to check, and it said I was logged in. Other times, it would be signing in.

**Comment by n8fr8** [comment]
I've improved underlying logging here so we can debug in the future. I also think the update to the latest Smack XMPP code might improve reconnet here.

**Comment by cstiens** [comment]
Seems to be working okay. We're going to keep our eye on it for a few days before closing.
