### ISSUE TITLE
Resend option?

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#400]
Hey @n8fr8 what happened to the resend icon on Android? If I remember correctly, there was a 'refresh' looking icon that resent an image to the same contact or group. In build 15.3.2 beta 2, you get the 'share' icon and 'send' which shows you a list of people to choose from.

*I've marked this as high because it affects the zomkyi script

**Comment by tiffrobo** [comment]
The resend option is available now. Though, when I tap hold to select a chat or audio in the chat view and select resend, it does not resend.

When I tap hold a photo, it opens the full screen view. Selecting resend from here brings up the 'choose a friend' list. It should skip that step and resend to the contact I originally sent it to.

Device: Samsung Galaxy S7
OS: Android 7.0
App version: 15.4.0-beta-1

**Comment by tiffrobo** [comment]
- Resend of photos is working. Resends to the contact you are chatting with. 
- Resend of http and https links works.
- Resend of an audio link does nothing. I tap hold and select resend, then resend option goes away and nothing happens. 

This is the same for single and group chat.

Device: Moto G play
OS: Android 6.0.1
Device: Moto X 
OS: Android 5.1

App version: 15.4 beta 2

**Comment by n8fr8** [comment]
oh now you want audio resending to, huh?!?! :P

**Comment by tiffrobo** [comment]
Working! Thanks!

Device: Moto E
OS: Android 5.1

Device: Moto G play
OS: Android 6.0.1

Device: Moto X 
OS: Android 5.1

Build: 15.4.0 RC 1
