### ISSUE TITLE
when reinvited to group, subject/name is not set

### ISSUE THREAD

**Issue by n8fr8** [zom/Zom-Android-XMPP#413]
next time you sign-in/rejoin it is there, but not at first

**Comment by tiffrobo** [comment]
Didn't show initially, but when I tapped the group in my convo view, the overlay opened with the correct group name. 
(initially showed group23456)

Device: Moto E, Nexus 7, Moto G play
OS: Android 5.1, Android 5.1.1 (tablet), Android 6.0.1
Build: 15.5 beta 2
