### ISSUE TITLE
UI for multiple Zom Bots

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#420]

**Comment by n8fr8** [comment]
Need to finalize the chatbot JIDs for @N-Pex as well

**Comment by cstiens** [comment]
@n8fr8 UI and artwork is on the ios ticket: https://github.com/zom/Zom-iOS/issues/273

**Comment by N-Pex** [comment]
@n8fr8 Please have a look at https://github.com/zom/Zom-Android/pull/430. Could you please have a look at ServiceActivity.onBotClicked to wire it up correctly, I can't seem to get it to start the chat.

**Comment by tiffrobo** [comment]
I see the new UI for two Zombots; Zomkyi and Agu. They look great! Tapping on a zombot opens a chat, but it first 'pauses' on the Discover view.

Device: Moto E
OS: Android 5.1

Device: Moto G play
OS: Android 6.0.1

Device: Moto X 
OS: Android 5.1

Build: 15.4.0 RC 1

**Comment by cstiens** [comment]
@n8fr8 On my galaxy, there was quite a long pause on the discover tab before opening a chat with the bot. Long enough that I didn't think it worked. Have you seen this? I think we'd want to fix it before releasing.

**Comment by n8fr8** [comment]
It has to add the contact before it can open the chat... that can take a few seconds sometimes.
 Maybe I can add a "waiting" dialog

**Comment by cstiens** [comment]
Some feedback would be helpful!

**Comment by n8fr8** [comment]
Adding it now...
