### ISSUE TITLE
Update Losar Expression Pack

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#422]
Final edits ready on Tues, Feb 6

**Comment by cstiens** [comment]
@n8fr8 The complete updated losar pack is here (outside of the folders): https://github.com/zom/Zom-Assets/tree/master/stickers/losar

**Comment by n8fr8** [comment]
We need to keep all of our old stickers in there, since people are already using them. We can add the new ones, but we can't remove the old ones.

**Comment by N-Pex** [comment]
Oh, yeah. So I guess the new Losar stickers that were moved to the expression pack will be duplicates.

**Comment by n8fr8** [comment]
@N-Pex I processed the stickers a bit, trimming them, compressing them, and updated the Zom-Assets project, so you probably need to pull them down again.
