### ISSUE TITLE
Non-friend profile from group

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#450]
iOS ticket: https://github.com/zom/Zom-iOS/issues/568

**Comment by kckthx** [comment]
@cstiens @N-Pex 
![add-friend-android](https://user-images.githubusercontent.com/36669955/38270130-239eb4b6-3748-11e8-80aa-6603e89ef63d.png)

**Comment by kckthx** [comment]
![add-friend-android_0 0](https://user-images.githubusercontent.com/36669955/38327956-3886a100-380f-11e8-89a0-3299e57faa82.png)
![add-friend-android_0 1](https://user-images.githubusercontent.com/36669955/38327957-38984a54-380f-11e8-8e49-07c91e5e6620.png)
![add-friend-android_0 2](https://user-images.githubusercontent.com/36669955/38327958-38aa1c02-380f-11e8-8593-6f8469132226.png)
![add-friend-android_0 3](https://user-images.githubusercontent.com/36669955/38327959-38bec972-380f-11e8-9e64-88d1549c40f7.png)
@cstiens

**Comment by tiffrobo** [comment]
This is in and working!

Device: Moto E, Nexus 7, Moto G play
OS: Android 5.1, Android 5.1.1 (tablet), Android 6.0.1
Build: 15.5 beta 2

**Comment by tiffrobo** [comment]
I didn't notice at first, but there may be a bug. I see 'add friend' within the profile view for everyone (even myself) in the group roster, **EXCEPT** the owner. 

-I saw this on two out of three test devices

Steps taken:

- Group created.
- Tap group info and see roster
- Tap member see 'add soandso as friend'
- Tap myself see 'add soandso as friend'
- Tap owner (creator) of group and see their zom code and name.

Device: Moto E, Nexus 7, Moto G play
OS: Android 5.1, Android 5.1.1 (tablet), Android 6.0.1
Build: 15.5 beta 2

**Comment by N-Pex** [comment]
I think this will be fixed in the next build.

**Comment by tiffrobo** [comment]
I'm not seeing this anymore.

Device: Moto G play 
OS: Android 6.0.1
Device: Nexus 7 
OS: Android 5.1.1

Build: 15.5 beta 4
