### ISSUE TITLE
Android messages not going through to new OMEMO groups

### ISSUE THREAD

**Issue by tiffrobo** [zom/Zom-Android-XMPP#452]
- A new group chat is created. 
- This is a group with iOS and Android members. 
- OMEMO is turned on for everyone in the group. 

- Android can see all messages sent from both iOS and Android (media, audio, text)
- All Android messages sent are not received (media, audio, text). They show a clock as the 'delivery receipt'. 

Devices:  Samsung Galaxy S7
OS: Android 7.0

Device: Moto G play
OS: Android 6.0.1

Device: Moto X 
OS: Android 5.1

Android App version: 15.5 Beta 1

Devices: iPhone 7,  iPhone 6, iPad
OS: 11.2.2, OS: 10.3.3, OS: 10.3.2
iOS app version: 126

**Comment by tiffrobo** [comment]
I'm not seeing this issue in the latest build. Can we close it? 

Moto G play, Nexus 7, Moto E 
OS: Android 6.0.1, Android 5.1.1, Android 5.1
15.6.0-beta-3

**Comment by iamironrabbit** [comment]
Yes!
