### ISSUE TITLE
Integrate ProofMode

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#458]

**Comment by cstiens** [comment]
The toggle to turn on ProofMode will be in settings. See the organization here: https://github.com/zom/Zom-Android/issues/462

![proofmode_v2](https://user-images.githubusercontent.com/1434597/39008607-c8296d0e-43ce-11e8-9433-71bf773679b5.png)

**Comment by tiffrobo** [comment]
I know this is in the development phase, so I’m updating the ticket to help keep track of what we are seeing. 
Steps taken:

- Enable proofmode in settings. 
- Within a chat tap the camera option. 
- Camera opens with new proofmode camera. 
- Tap the 'circle' to take the picture and the app crashes. 
- App does not relaunch automatically. 

Moto G play, Nexus 7
OS: Android 6.0.1, Android 5.1.1
App build: 15.6.0-beta-2

**Comment by tiffrobo** [comment]
This is working! It's pretty cool when you know what it is!
Moving forward we could enhance the sender and receiver UI. 

Device: Moto G play, Moto E
OS: Android 6.0.1, Android 5.1
App version: 15.6.0-beta-6
