### ISSUE TITLE
New "Add Friends" UI

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#467]
@N-Pex the design specs and assets are on the iOS ticket: https://github.com/zom/Zom-iOS/issues/590

**Comment by kckthx** [comment]
[Nearby.zip](https://github.com/zom/Zom-Android/files/1956327/Nearby.zip)
@N-Pex @cstiens 

Nearby icon for Add Friends. Png and svg

**Comment by N-Pex** [comment]
@kckthx Do you also have the qr and the "..." icon in svg please?

@n8fr8 Checking in a PR for this soon, adding a stub for Nearby in OnboardingManager.inviteNearby

**Comment by kckthx** [comment]
[QR-More.zip](https://github.com/zom/Zom-Android/files/1984414/QR-More.zip)
@N-Pex

**Comment by N-Pex** [comment]
@kckthx Thanks! Would you mind making the "more" svg a square drawing (or page), seems like my scripts can't handle if it's not.

**Comment by kckthx** [comment]
yes here you go! 
@N-Pex 
[More-Square.svg.zip](https://github.com/zom/Zom-Android/files/1984506/More-Square.svg.zip)

**Comment by N-Pex** [comment]
That was fast, thanks!

**Comment by N-Pex** [comment]
@n8fr8 Sending this to you now, for the Nearby stuff.

**Comment by tiffrobo** [comment]
It's all there and seems to fit well on various screen sizes. 

Moto G play, Nexus 7, Moto E 
OS: Android 6.0.1, Android 5.1.1, Android 5.1
15.6.0-beta-1
