### ISSUE TITLE
Group member list not refreshing in time

### ISSUE THREAD

**Issue by cstiens** [zom/Zom-Android-XMPP#468]

**Comment by n8fr8** [comment]
When a user is invited to a new group, and they open the group info screen, there is often no members listed, due to the member list not refreshing or loading in time.

**Comment by N-Pex** [comment]
Should work now. The member list was fetched before a listener was attached and when the listener was attached it was not updated with current state. Fixed now.

**Comment by n8fr8** [comment]
Superb!

**Comment by tiffrobo** [comment]
This seems to be working!

Device: Moto G play 
OS: Android 6.0.1
Device: Nexus 7 
OS: Android 5.1.1
Build: 15.5 beta 4
