### ISSUE TITLE
can not signin with xmpp server ip

### ISSUE THREAD

**Issue by vahidnety** [zom/Zom-Android-XMPP#472]
Hi
I am can signin with my xmpp server ip and username on Zom iOS version but cannot signin on Zom Android version with the same credential.
I have turned off TLS as well. but still same outcome.
Should I setup specifically for Android version?

**Comment by n8fr8** [comment]
You need to have a host name of some kind. You can enter the IP address in the "connect server" value.

**Comment by vahidnety** [comment]
Still same issue.

**Comment by fakihi** [comment]
I have the same issue. I can connect with other xmpp clients, I can connect with the Zom iOS version but I can't connect with Zom Android. I thought it is the hostname verification, but disabling it does not solve the problem.

**Comment by silatel** [comment]
I have the same issue. I can connect with other xmpp clients, I can connect with the Zom iOS version but I can't connect with Zom Android. I thought it is the hostname verification, but disabling it does not solve the problem.

**Comment by iamironrabbit** [comment]
We have released Zom 2.0 and we are now using Matrix (https://matrix.org) as our messaging protocol. 

You can find the new project here: https://github.com/zom/zom-android-matrix

If you want to still use XMPP, please move to the Conversations app on Android, or ChatSecure on iOS. We will keep our home.zom.im XMPP server up for another few weeks, so please migrate to a new XMPP host. 

Apologies for any inconvenience, and please try our new release. It is much more stable, with support for large encrypted groups, expanded file sharing, and more coming soon. You can also sign in on multiple devices, include our beta web UI: https://web.nang.zom.im/ 
You can use any Matrix compatible client app with encryption, and all messages and state will sync between devices.
