### ISSUE TITLE
compliance = happiness

### ISSUE THREAD

**Issue by unicorntaco** [zom/Zom-Android-XMPP#494]
Offering new users a choice of fully compliant public servers is a great idea, isn't it?

https://github.com/iNPUTmice/ComplianceTester

It can be vexing to have an iOS user install zom only to have them land a JID on a server missing all the great XEP.

**Comment by brighterness** [comment]
Yes! This!!

list
[https://compliance.conversations.im](https://compliance.conversations.im)

Apparently the mice who takes no input on Conversations app default [social features](https://github.com/kriztan/Pix-Art-Messenger) has morphed the tester into a suite:

[https://github.com/iNPUTmice/caas](https://github.com/iNPUTmice/caas)

to which anyone may contribute without the complexity (for me) of "pull requests".

**Comment by abeluck** [comment]
Currently our server scores an 88% https://compliance.conversations.im/server/home.zom.im/

We will be working over the next months to improve this.

**Comment by ghost** [comment]
still 88%

**Comment by ghost** [comment]
83% now...

**Comment by abeluck** [comment]
100% now :grin: 

We've no interest in fixing "Discovering Alternative XMPP Connection Methods (HTTP)" and as for HTTP Upload with CORS, the prosody module we're using already supports it, so something is wrong with the test.

**Comment by abeluck** [comment]
@iamironrabbit please close this issue
