### ISSUE TITLE
Link share from iOS to Android via email not working

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-Android-XMPP#50]
When I click on the Zom link from shared from Add Buddy option in iOS to Android, it's taking me to the download page.

Not sure if the bug is from Zom Android or iOS

**Comment by gekhung** [comment]
Clarification: It takes me to the Zom download page if Zom is closed and if it's open, then Zom appears for a second and then disappears.

**Comment by n8fr8** [comment]
Can you clarify on this? Are you opening the link in Android or iOS?

**Comment by gekhung** [comment]
opening link in Android.This has been a while, not sure if the bug is still there.

**Comment by gekhung** [comment]
Just checked again.

From iOS, I clicked on 'Add friends to Zom', Selected 'Share Link' option, and sent it to my email.

I clicked on the link from my Android phone and had option to select from several apps, I clicked on Zom. I landed on the email with the link. Zom didn't open. I tried this with while Zom is open and closed. It was same both times.

**Comment by n8fr8** [comment]
Okay thanks. This is with the Play build or HockeyApp?

**Comment by gekhung** [comment]
HockeyApp.

**Comment by n8fr8** [comment]
Alright, will try to reproduce here. I think there is something wrong with the way iOS is sending links.

**Comment by n8fr8** [comment]
just tested. fixed!
