### ISSUE TITLE
Onboarding - Language option

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-Android-XMPP#54]
In the 'Welcome to Zom' page, when I select Tibetan from the language option, it doesn't switch to Tibetan.

Also, would it make sense to remove languages that are not translated at the moment from the option?

**Comment by n8fr8** [comment]
Looking into both... I will likely push out another release to fix top issues in next day or two.

**Comment by lphooge** [comment]
Maybe the translations for the strings on the language selection page are missing?
Had the same for german, I selected it, but it remained english. 
However on the next page some texts where indeed in german.

By the way, is help with translations needed?

**Comment by n8fr8** [comment]
This is done now... though still a few bugs in display, it definitely switches language.

**Comment by n8fr8** [comment]
String translations is here, btw: https://www.transifex.com/zom/zom-messenger
