### ISSUE TITLE
Photos received in Android device

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-Android-XMPP#55]
I received a photo (from my iOS device) and  sent a different photo to the iOS device from Android. Photo from iOS took a little time to receive. I checked Zom after 5-10 minutes and in Android, instead of showing the two different photos received and sent, it was showing the one that I received in place of the photo I sent. It switched back to the actual photo in less than a minute.

**Comment by gekhung** [comment]
And then I received a sticker of Sindu from the iOS device, and images received and sent prior to that became Sindu.

**Comment by n8fr8** [comment]
I think this is fixed now in the latest HockeyApp release, with the improved image loading code.
