### ISSUE TITLE
OTR-Data chunk length incompatible sending from Android to iOS

### ISSUE THREAD

**Issue by davidchiles** [zom/Zom-Android-XMPP#66]
Looks like in 62786b17b9650b86f50d59aa0af869d2e28b90a6 @n8fr8  changed the `MAX_CHUNK_LENGTH` to be half what it was previously. We've always sent our `GET` requests using [`16384`](https://github.com/ChatSecure/OTRKit/blob/master/OTRKit/OTRData/OTRDataHandler.m#L31) as the maximum chunk length. So for any file greater than `8192` bytes we get:

```
HTTP/1.1 400 Range must be at most 8192
Request-Id: DF9BC14C-3557-4139-9465-6ADE4F494D68
```

The [spec](https://dev.guardianproject.info/projects/gibberbot/wiki/OTRDATA_Specifications) says

```
The maximum packet size is 65535.
```

What's the true maximum chunk length? Why was it changed?

**Comment by n8fr8** [comment]
Dang it. I meant to change the range we were using to 8k, but still allow others to use a larger one. As a side note, I was debugging issues we were having with transferring large files, and found that using 8k made it more reliable. What if we change to 8k on iOS? I will still fix the MAX supported on our side for now.

**Comment by n8fr8** [comment]
Some progress here, but not yet perfect. It seems I can send content now, but I can't receive. That means the 8kb chunk I am request from the iOS OFFER is not working. I will change back to 16kb to see if it works, but I really do want to use 8kb.
