### ISSUE TITLE
Translation outdated

### ISSUE THREAD

**Issue by pejakm** [zom/Zom-Android-XMPP#72]
I compiled and installed Zom just to notice that Serbian translation is a mess. Serbian is 100% finished on Transifex, please update to it before final release.

**Comment by n8fr8** [comment]
Yes, we haven't pulled it down in awhile. Will do before the next release.

**Comment by winter20161** [comment]
Is the "zomstrings.xml" on transifex still valid? 
I noticed that the newest version 15.0.1.932 has many phrases that do not show up in the "zomstrings.xml". In spite of this, some languages are fully translated (e.g. de, jp, zh-cn), while some are not (eg. ko, nl ... etc.).

**Comment by n8fr8** [comment]
We've pulled the latest strings, and now pushed our source translations into tfx. Thanks for the notice and help.
