### ISSUE TITLE
Zom String in Transifex showing Chatsecure

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-Android-XMPP#73]
I have listed them here by string #

21 
43 
48 
59 
60 
64 
92
93
113
116
305
344
385
397
439
482
![chatsecure](https://cloud.githubusercontent.com/assets/11950115/13989969/f33a8e6e-f0e8-11e5-8e07-81f40dfedd1a.png)

**Comment by n8fr8** [comment]
Just a note, don't use the "#" symbol on Github, as that is used to link to issue tickets.

Otherwise, is this on Android or iOS? I thought you mentioned Zom iOS before?

**Comment by gekhung** [comment]
Just removed the '#' symbol. I said iOS by mistake. It's the Zom Messenger organization/project that you started in Transifex: https://www.transifex.com/zom/

**Comment by n8fr8** [comment]
okay
