### ISSUE TITLE
Zom started a separate chat instead of continuing with old one

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-Android-XMPP#77]
I was chatting with FP and while responding to her last message, it didn't appear in the chat we were in. 

I went back to chat page, there were two chats with the same username. The old one showed FP online and the new one had her offline. 

Each time I sent a message in the old chat, it shows in the new one instead.

I went to the Contacts page and opened chat with FP from there, and it took me to the new chat.

FP didn't get those two messages.

**Comment by n8fr8** [comment]
Do you have more than one accounts setup? Are they both connected? I think it is getting confused about who you want to chat with her as.

**Comment by gekhung** [comment]
Oh yes, i was testing the 'add account' option in 'My Accounts' around the time we were chatting. How can I delete/remove the second account? Now that I look back at the 'Me' page, the second account has replaced the first one. Shouldn't the first account be the default one?

**Comment by n8fr8** [comment]
Yes I think that is the bug.. it should keep your first account as the default one, or better indicate which one is active.

**Comment by n8fr8** [comment]
Also, it should use the correct account that you added a contact with, and not switch to the other one, even if it is the default.

**Comment by n8fr8** [comment]
You can delete the second account by tapping it on the my accounts list, and then open the menu and choose "delete".

**Comment by gekhung** [comment]
Got it. Thanks!

**Comment by gekhung** [comment]
Second account deleted and then I tried sending messages again, but my message doesn't appear in the chat. The separate chat also doesn't appear.

**Comment by n8fr8** [comment]
Can you press and hold on the one account for a few seconds? It should set it to by the "default"

**Comment by n8fr8** [comment]
Otherwise, try shutdown/restart of the app.

**Comment by gekhung** [comment]
Tried that as well and didn't work. If there is only one account left, shouldn't Zom automatically set it as default?

I'm restarting Zom now.

**Comment by n8fr8** [comment]
It should. This def a big bug in the new multi account stuff. I can get it fixed this weekend.
