### ISSUE TITLE
New user notification

### ISSUE THREAD

**Issue by jodiejones** [zom/Zom-Android-XMPP#81]
I know we've been through a few iterations of the notification message that appears when a user clicks on a share link. Right now, the notification that appears says "Your friend said YES to ZOM!" for both users. This is confusing for the user who is clicking on the link. It only makes sense for the user who shared the link. ie. Tenchoe shared her link with me in txt mssg. I clicked on the link and I get a notification that says "your friend said YES to Zom" but Tenchoe didn't say yes, I'm the one who said YES so this notification doesn't make sense for me, only for Tenchoe.

So, we go with a generic message that will make sense for both users:
"You're now ready to Zom with [username]"
Or we need a different notification for the user who clicks on the share link
"You've added a friend to Zom!"

**Comment by n8fr8** [comment]
I think a generic message that just says you are connected with this person is the best.

**Comment by jodiejones** [comment]
OK, can it have the username or is this too complicated? ie. You're now ready to Zom with [username] - user name is automatically generated
but if this is too complicated then it could just say "You're now friends in Zom!" b/c the user name is at the top of the notification

Also, one more thing, when you click on the notification it should open a chat window. Right now it takes the user who sent the share link to the contact list

**Comment by n8fr8** [comment]
okay... yes, that is a bug. it should open to a chat.
