### ISSUE TITLE
Friend invite link in Wechat takes user to Download page

### ISSUE THREAD

**Issue by gekhung** [zom/Zom-Android-XMPP#85]
User 1: Samsung S3 4.4.2 
User 2: Carbon 6.0.1

In one of the previous versions, users are prompt to go to Zom when clicked on invite link in Wechat.
The latest version takes user 1 to a blank page and User 2 to the Zom download page instead of the app.

When sending an invite in Wechat, user gets the option to go "Back to Previous App' or 'Stay in Wechat' which is great!

**Comment by n8fr8** [comment]
Don't think we can do anything more for Wechat users right now.
