### ISSUE TITLE
trying to import the Zom in Android studio.

### ISSUE THREAD

**Issue by gurpreetlucky** [zom/Zom-Android-XMPP#90]
while importing the project in android studio below error .

INFO - ls.idea.gradle.GradleSyncState - Sync with Gradle for project 'Zom-Android-master' failed: Configuration with name 'default' not found.

Not sure which default value its searching. 
while google it saying that might its submodules are not in sync.

**Comment by mcanonic** [comment]
Did you use git? or you just download the zip file?
I did not know the URL for the git clone (did you know?) and the unzip report me some warning/error:
finishing deferred symbolic links:
  Zom-Android-master/app/src/main/res/values-he -> values-iw
lchmod (file attributes) error: Function not implemented
  Zom-Android-master/app/src/main/res/values-id -> values-in
lchmod (file attributes) error: Function not implemented

Did you get the same problem?
M

**Comment by mcanonic** [comment]
Did you run: git submodule update --init 
after the git clone command?
M

**Comment by n8fr8** [comment]
Please use git clone to get the project, and run the git submodule update --init command
