### ISSUE TITLE
Show contacts from roster and allow to add them to groups

### ISSUE THREAD

**Issue by rasos** [zom/Zom-Android-XMPP#97]
When I use my own xmpp server, it is likely that it offers a user list as a roster.
It would be great to be able to 
1. list those users from the roster, so that I can start a chat
2. invite users from that roster
3. define roles, as specified in [XEP-0045](http://www.xmpp.org/extensions/xep-0045.html#associations)

**Comment by iamironrabbit** [comment]
This should be implemented now, and part of our next release. You can add anyone to groups that is in your own roster, and you can make others group moderators.

**Comment by tiffrobo** [comment]
This is in and working! 

Moto G play, Nexus 7, Moto E 
OS: Android 6.0.1, Android 5.1.1, Android 5.1
15.6.0-beta-3
